import { jsPDF } from 'jspdf';
import { toast } from 'sonner';
import {
  FileText,
  Image as ImageIcon,
  FileSpreadsheet,
  GraduationCap,
  Users,
  BookOpen,
  FlaskConical,
  BookMarked,
  UsersRound,
  Building2,
  Users2,
} from 'lucide-react';
import type { EvidencePreviewData } from '@/components/shared/EvidencePreviewDialog';
import { evidenceReviewKey } from '@/store/slices/evidenceReviewSlice';
import { EvidenceItem } from '../hod-configs';

// ---------------------------------------------------------------------------
// Shared presentation helpers for the HOD Evidence Review & Approval Queue
// ---------------------------------------------------------------------------

export const STATUS_META: Record<EvidenceItem['status'], { label: string; badge: string; dot: string }> = {
  pending: { label: 'Pending', badge: 'bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400', dot: 'bg-amber-500' },
  approved: { label: 'Approved', badge: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400', dot: 'bg-green-500' },
  rejected: { label: 'Rejected', badge: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400', dot: 'bg-red-500' },
  'changes-requested': { label: 'Changes Requested', badge: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400', dot: 'bg-purple-500' },
};

export const REPO_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  Academic: GraduationCap,
  Course: BookMarked,
  Faculty: Users,
  Student: BookOpen,
  Research: FlaskConical,
  'Student Dev': UsersRound,
  Infrastructure: Building2,
  Alumni: Users2,
};

export const REPO_ACCENT: Record<string, string> = {
  Academic: 'text-violet-600 bg-violet-500/10 border-violet-500/30',
  Course: 'text-sky-600 bg-sky-500/10 border-sky-500/30',
  Faculty: 'text-indigo-600 bg-indigo-500/10 border-indigo-500/30',
  Student: 'text-emerald-600 bg-emerald-500/10 border-emerald-500/30',
  Research: 'text-pink-600 bg-pink-500/10 border-pink-500/30',
  'Student Dev': 'text-rose-600 bg-rose-500/10 border-rose-500/30',
  Infrastructure: 'text-amber-600 bg-amber-500/10 border-amber-500/30',
  Alumni: 'text-teal-600 bg-teal-500/10 border-teal-500/30',
};

export function getFileIcon(item: EvidenceItem) {
  switch (item.fileType) {
    case 'pdf': return <FileText className="h-4 w-4 text-red-500 shrink-0" />;
    case 'image': return <ImageIcon className="h-4 w-4 text-blue-500 shrink-0" />;
    case 'excel': return <FileSpreadsheet className="h-4 w-4 text-green-500 shrink-0" />;
    default: return <FileText className="h-4 w-4 text-indigo-500 shrink-0" />;
  }
}

export function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// ---------------------------------------------------------------------------
// Mock document URL generation (so Preview / Download actually work)
// ---------------------------------------------------------------------------

const urlCache = new Map<string, string>();

function buildPdfUrl(title: string, subtitle: string): string {
  const doc = new jsPDF();
  doc.setFillColor(241, 245, 249);
  doc.rect(0, 0, 210, 297, 'F');
  doc.setFillColor(255, 255, 255);
  doc.roundedRect(12, 12, 186, 273, 3, 3, 'F');
  doc.setDrawColor(203, 213, 225);
  doc.setLineWidth(0.3);
  doc.rect(12, 12, 186, 273);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(51, 65, 85);
  doc.text(title, 20, 32);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(100, 116, 139);
  doc.text(subtitle, 20, 40);
  doc.setFontSize(9);
  doc.setTextColor(148, 163, 184);
  doc.text('AccreditPro — Evidence Repository (auto-generated preview for HOD review)', 20, 258);
  doc.text('This document preview is generated for demonstration purposes.', 20, 264);
  return String(doc.output('bloburl'));
}

function buildImageUrl(title: string): string {
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="1100">` +
    `<rect width="100%" height="100%" fill="#f1f5f9"/>` +
    `<rect x="30" y="30" width="740" height="1040" rx="10" fill="#ffffff" stroke="#cbd5e1"/>` +
    `<text x="400" y="110" font-family="Arial, sans-serif" font-size="30" font-weight="bold" text-anchor="middle" fill="#334155">${title}</text>` +
    `<text x="400" y="150" font-family="Arial, sans-serif" font-size="16" text-anchor="middle" fill="#64748b">Scanned document — preview generated by AccreditPro</text>` +
    `<rect x="60" y="190" width="680" height="480" rx="8" fill="#e2e8f0"/>` +
    `<text x="400" y="430" font-family="Arial, sans-serif" font-size="18" text-anchor="middle" fill="#94a3b8">[ Document Image ]</text>` +
    `<rect x="60" y="700" width="680" height="120" rx="8" fill="#f8fafc" stroke="#e2e8f0"/>` +
    `<text x="400" y="745" font-family="Arial, sans-serif" font-size="13" text-anchor="middle" fill="#64748b">Uploaded to the department evidence repository</text>` +
    `</svg>`;
  return `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;
}

function buildTextUrl(title: string, category: string): string {
  const text = `${title}\nCategory: ${category}\n\nGenerated by AccreditPro — HOD Evidence Review.\nThis file is a mock preview for demonstration purposes.`;
  return `data:text/plain;charset=utf-8,${encodeURIComponent(text)}`;
}

export function getDocUrl(item: EvidenceItem): string {
  const cached = urlCache.get(item.id);
  if (cached) return cached;
  const url =
    item.fileType === 'pdf'
      ? buildPdfUrl(item.documentName, `${item.section} • ${item.documentCategory}`)
      : item.fileType === 'image'
        ? buildImageUrl(item.documentName)
        : buildTextUrl(item.documentName, item.documentCategory);
  urlCache.set(item.id, url);
  return url;
}

export function downloadItem(item: EvidenceItem) {
  const link = document.createElement('a');
  link.href = getDocUrl(item);
  link.download = item.documentName;
  link.click();
  toast.success(`Downloading ${item.documentName}`);
}

export function buildPreviewData(item: EvidenceItem): EvidencePreviewData {
  return {
    id: item.id,
    fileName: item.documentName,
    fileType: item.fileType === 'image' ? 'png' : item.fileType === 'excel' ? 'xlsx' : item.fileType === 'doc' ? 'doc' : 'pdf',
    fileSize: item.fileSize,
    dataUrl: getDocUrl(item),
    uploadedAt: formatDate(item.uploadDate),
    uploadedBy: item.uploadedBy,
    status: item.status === 'pending' ? 'under-review' : item.status,
    category: `${item.repository} • ${item.section}`,
  };
}

// ---------------------------------------------------------------------------
// Shared-store sync
// ---------------------------------------------------------------------------

export interface EvidenceGroup {
  section: string;
  items: EvidenceItem[];
}

export interface RepoGroup {
  repository: string;
  sections: EvidenceGroup[];
  total: number;
}

/** Group evidence items by repository → section (category), in a stable order. */
export function buildRepoGroups(filteredItems: EvidenceItem[]): RepoGroup[] {
  const map = new Map<string, RepoGroup>();
  for (const item of filteredItems) {
    let group = map.get(item.repository);
    if (!group) {
      group = { repository: item.repository, sections: [], total: 0 };
      map.set(item.repository, group);
    }
    let section = group.sections.find((s) => s.section === item.section);
    if (!section) {
      section = { section: item.section, items: [] };
      group.sections.push(section);
    }
    section.items.push(item);
    group.total += 1;
  }
  const order = ['Academic', 'Course', 'Faculty', 'Student', 'Research', 'Student Dev', 'Infrastructure', 'Alumni'];
  return [...map.values()].sort((a, b) => {
    const ai = order.indexOf(a.repository);
    const bi = order.indexOf(b.repository);
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  });
}

/** Overlay shared-store review decisions onto the base evidence items. */
export function applyReviewOverrides(
  base: EvidenceItem[],
  year: string,
  reviews: Record<string, { status: EvidenceItem['status']; note?: string; reviewedBy?: string; reviewDate?: string }>
): EvidenceItem[] {
  return base.map((item) => {
    const review = reviews[evidenceReviewKey(year, item.repository, item.section, item.documentCategory)];
    if (!review) return item;
    return {
      ...item,
      status: review.status,
      reviewNote: review.note ?? item.reviewNote,
      reviewedBy: review.reviewedBy ?? item.reviewedBy,
      reviewDate: review.reviewDate ?? item.reviewDate,
    };
  });
}
