import {
  DepartmentStats,
  FacultyRecord,
  StudentRecord,
  ResearchRecord,
  AcademicRecord,
  CSVUploadRecord,
  MissingRecord,
  MissingDocument,
} from './types';

export const departmentStats: DepartmentStats = {
  facultyRecords: 42,
  studentRecords: 856,
  researchRecords: 127,
  documentsUploaded: 234,
  pendingReviews: 8,
  repositoryCompletion: 78.5,
};

export const facultyRecords: FacultyRecord[] = [
  {
    id: '1',
    name: 'Dr. Anita Sharma',
    designation: 'Professor',
    qualification: 'Ph.D. Computer Science',
    experience: 18,
    specialization: 'Machine Learning',
    publications: 45,
    status: 'active',
  },
  {
    id: '2',
    name: 'Dr. Rajesh Kumar',
    designation: 'Associate Professor',
    qualification: 'Ph.D. Data Science',
    experience: 12,
    specialization: 'Big Data Analytics',
    publications: 32,
    status: 'active',
  },
  {
    id: '3',
    name: 'Prof. Meera Patel',
    designation: 'Assistant Professor',
    qualification: 'M.Tech + Ph.D.',
    experience: 8,
    specialization: 'Cloud Computing',
    publications: 18,
    status: 'active',
  },
  {
    id: '4',
    name: 'Dr. Suresh Nair',
    designation: 'Professor',
    qualification: 'Ph.D. Networks',
    experience: 22,
    specialization: 'Network Security',
    publications: 56,
    status: 'active',
  },
  {
    id: '5',
    name: 'Dr. Priya Deshmukh',
    designation: 'Associate Professor',
    qualification: 'Ph.D. AI',
    experience: 10,
    specialization: 'Natural Language Processing',
    publications: 28,
    status: 'on_leave',
  },
  {
    id: '6',
    name: 'Prof. Vikram Singh',
    designation: 'Assistant Professor',
    qualification: 'M.Tech + Ph.D.',
    experience: 6,
    specialization: 'IoT Systems',
    publications: 12,
    status: 'active',
  },
  {
    id: '7',
    name: 'Dr. Kavita Joshi',
    designation: 'Professor',
    qualification: 'Ph.D. Software Eng.',
    experience: 20,
    specialization: 'Software Architecture',
    publications: 38,
    status: 'active',
  },
  {
    id: '8',
    name: 'Dr. Amit Verma',
    designation: 'Associate Professor',
    qualification: 'Ph.D. Algorithms',
    experience: 14,
    specialization: 'Algorithm Design',
    publications: 25,
    status: 'retired',
  },
];

export const studentRecords: StudentRecord[] = [
  {
    id: '1',
    name: 'Rahul Mehta',
    rollNumber: 'CS2024001',
    program: 'B.Tech CSE',
    year: 1,
    cgpa: 8.7,
    status: 'active',
  },
  {
    id: '2',
    name: 'Sneha Gupta',
    rollNumber: 'CS2024002',
    program: 'B.Tech CSE',
    year: 1,
    cgpa: 9.2,
    status: 'active',
  },
  {
    id: '3',
    name: 'Arjun Patel',
    rollNumber: 'CS2023015',
    program: 'B.Tech CSE',
    year: 2,
    cgpa: 8.4,
    status: 'active',
  },
  {
    id: '4',
    name: 'Divya Sharma',
    rollNumber: 'CS2023022',
    program: 'B.Tech CSE',
    year: 2,
    cgpa: 9.0,
    status: 'active',
  },
  {
    id: '5',
    name: 'Karan Singh',
    rollNumber: 'CS2022008',
    program: 'B.Tech CSE',
    year: 3,
    cgpa: 7.8,
    status: 'active',
  },
  {
    id: '6',
    name: 'Priya Nair',
    rollNumber: 'CS2022011',
    program: 'B.Tech CSE',
    year: 3,
    cgpa: 8.9,
    status: 'active',
  },
  {
    id: '7',
    name: 'Aditya Joshi',
    rollNumber: 'CS2021003',
    program: 'B.Tech CSE',
    year: 4,
    cgpa: 8.1,
    status: 'active',
  },
  {
    id: '8',
    name: 'Neha Kulkarni',
    rollNumber: 'CS2021019',
    program: 'M.Tech CSE',
    year: 1,
    cgpa: 9.4,
    status: 'active',
  },
];

export const researchRecords: ResearchRecord[] = [
  {
    id: '1',
    title: 'Deep Learning Approaches for Medical Image Segmentation',
    authors: 'Dr. Anita Sharma, Rahul Mehta',
    journal: 'IEEE Trans. Medical Imaging',
    year: 2024,
    impactFactor: 8.9,
    type: 'journal',
    status: 'published',
  },
  {
    id: '2',
    title: 'Federated Learning for Privacy-Preserving Analytics',
    authors: 'Dr. Rajesh Kumar, Sneha Gupta',
    journal: 'ACM Computing Surveys',
    year: 2024,
    impactFactor: 16.6,
    type: 'journal',
    status: 'published',
  },
  {
    id: '3',
    title: 'Edge Computing Framework for Real-time IoT',
    authors: 'Prof. Vikram Singh',
    journal: 'IEEE IoT Journal',
    year: 2024,
    impactFactor: 10.6,
    type: 'journal',
    status: 'accepted',
  },
  {
    id: '4',
    title: 'Transformer-based NLP for Indian Languages',
    authors: 'Dr. Priya Deshmukh, Arjun Patel',
    journal: 'EMNLP 2024',
    year: 2024,
    impactFactor: 0,
    type: 'conference',
    status: 'under_review',
  },
  {
    id: '5',
    title: 'Quantum Computing Algorithms for Optimization',
    authors: 'Dr. Suresh Nair',
    journal: 'Nature Computational Science',
    year: 2024,
    impactFactor: 12.0,
    type: 'journal',
    status: 'published',
  },
  {
    id: '6',
    title: 'Patent: AI-based Plagiarism Detection System',
    authors: 'Dr. Kavita Joshi, Dr. Amit Verma',
    journal: 'Indian Patent Office',
    year: 2024,
    impactFactor: 0,
    type: 'patent',
    status: 'published',
  },
];

export const academicRecords: AcademicRecord[] = [
  {
    id: '1',
    category: 'Curriculum',
    title: 'Syllabus Revision 2024-25',
    academicYear: '2024-25',
    status: 'completed',
    lastUpdated: '2024-12-15',
    completionPercentage: 100,
  },
  {
    id: '2',
    category: 'Curriculum',
    title: 'Course Outcomes Mapping',
    academicYear: '2024-25',
    status: 'in_progress',
    lastUpdated: '2024-12-20',
    completionPercentage: 75,
  },
  {
    id: '3',
    category: 'Examination',
    title: 'Internal Assessment Records',
    academicYear: '2024-25',
    status: 'completed',
    lastUpdated: '2024-12-10',
    completionPercentage: 100,
  },
  {
    id: '4',
    category: 'Examination',
    title: 'University Exam Results',
    academicYear: '2024-25',
    status: 'pending',
    lastUpdated: '2024-11-30',
    completionPercentage: 40,
  },
  {
    id: '5',
    category: 'Placement',
    title: 'Placement Statistics',
    academicYear: '2024-25',
    status: 'in_progress',
    lastUpdated: '2024-12-18',
    completionPercentage: 65,
  },
  {
    id: '6',
    category: 'Infrastructure',
    title: 'Lab Equipment Inventory',
    academicYear: '2024-25',
    status: 'completed',
    lastUpdated: '2024-12-05',
    completionPercentage: 100,
  },
  {
    id: '7',
    category: 'Quality',
    title: 'Student Feedback Analysis',
    academicYear: '2024-25',
    status: 'pending',
    lastUpdated: '2024-11-25',
    completionPercentage: 20,
  },
  {
    id: '8',
    category: 'Quality',
    title: 'Faculty Performance Report',
    academicYear: '2024-25',
    status: 'in_progress',
    lastUpdated: '2024-12-12',
    completionPercentage: 55,
  },
];

export const uploadHistory: CSVUploadRecord[] = [
  {
    id: '1',
    fileName: 'faculty_data_2024.csv',
    category: 'faculty',
    uploadedAt: '2024-12-20 14:30',
    recordsCount: 42,
    validRecords: 40,
    invalidRecords: 2,
    status: 'approved',
    uploadedBy: 'Dr. Anita Sharma',
  },
  {
    id: '2',
    fileName: 'student_enrollment_sem1.csv',
    category: 'student',
    uploadedAt: '2024-12-19 10:15',
    recordsCount: 320,
    validRecords: 318,
    invalidRecords: 2,
    status: 'approved',
    uploadedBy: 'Prof. Meera Patel',
  },
  {
    id: '3',
    fileName: 'research_publications_2024.csv',
    category: 'research',
    uploadedAt: '2024-12-18 16:45',
    recordsCount: 28,
    validRecords: 28,
    invalidRecords: 0,
    status: 'approved',
    uploadedBy: 'Dr. Rajesh Kumar',
  },
  {
    id: '4',
    fileName: 'academic_records_q4.csv',
    category: 'academic',
    uploadedAt: '2024-12-17 09:00',
    recordsCount: 15,
    validRecords: 14,
    invalidRecords: 1,
    status: 'pending',
    uploadedBy: 'Dr. Kavita Joshi',
  },
  {
    id: '5',
    fileName: 'student_placement_data.csv',
    category: 'student',
    uploadedAt: '2024-12-16 11:30',
    recordsCount: 85,
    validRecords: 82,
    invalidRecords: 3,
    status: 'rejected',
    uploadedBy: 'Prof. Vikram Singh',
  },
  {
    id: '6',
    fileName: 'faculty_publications_update.csv',
    category: 'faculty',
    uploadedAt: '2024-12-15 13:20',
    recordsCount: 18,
    validRecords: 18,
    invalidRecords: 0,
    status: 'approved',
    uploadedBy: 'Dr. Suresh Nair',
  },
];

export const missingRecords: MissingRecord[] = [
  {
    category: 'Faculty',
    item: 'Faculty Development Programs attended',
    priority: 'high',
    deadline: '2025-01-15',
  },
  {
    category: 'Student',
    item: 'Higher Education progression data',
    priority: 'high',
    deadline: '2025-01-10',
  },
  {
    category: 'Research',
    item: 'Consultancy projects details',
    priority: 'medium',
    deadline: '2025-01-20',
  },
  {
    category: 'Academic',
    item: 'Value Added Courses list',
    priority: 'medium',
    deadline: '2025-01-25',
  },
  {
    category: 'Research',
    item: 'MoU and Collaboration documents',
    priority: 'low',
    deadline: '2025-02-01',
  },
  {
    category: 'Academic',
    item: 'Alumni feedback compilation',
    priority: 'low',
    deadline: '2025-02-10',
  },
];

export const missingDocuments: MissingDocument[] = [
  {
    name: 'NAAC SSR Criterion 2.1 Supporting Documents',
    category: 'Accreditation',
    required: true,
    deadline: '2025-01-15',
  },
  {
    name: 'Faculty Appraisal Reports 2024',
    category: 'Faculty',
    required: true,
    deadline: '2025-01-10',
  },
  {
    name: 'Student Satisfaction Survey Results',
    category: 'Quality',
    required: true,
    deadline: '2025-01-20',
  },
  {
    name: 'Lab Utilization Reports',
    category: 'Infrastructure',
    required: false,
    deadline: '2025-01-25',
  },
  {
    name: 'Industry Collaboration Agreements',
    category: 'Research',
    required: true,
    deadline: '2025-02-01',
  },
  {
    name: 'Best Practices Documentation',
    category: 'Quality',
    required: false,
    deadline: '2025-02-15',
  },
];

export const completionByCategory = [
  { category: 'Curriculum', completion: 92, total: 12, filled: 11 },
  { category: 'Teaching & Learning', completion: 85, total: 18, filled: 15 },
  { category: 'Research', completion: 78, total: 15, filled: 12 },
  { category: 'Infrastructure', completion: 88, total: 8, filled: 7 },
  { category: 'Student Support', completion: 65, total: 20, filled: 13 },
  { category: 'Governance', completion: 70, total: 10, filled: 7 },
  { category: 'Innovation', completion: 55, total: 12, filled: 7 },
  { category: 'Best Practices', completion: 45, total: 8, filled: 4 },
];
