export interface ExamFieldConfig {
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'select' | 'currency' | 'percentage';
  required?: boolean;
  options?: string[];
  placeholder?: string;
}

export interface ExamTabConfig {
  id: string;
  label: string;
  icon: string;
  description: string;
  fields: ExamFieldConfig[];
  sampleData: Record<string, string | number>[];
}

export const examTabConfigs: ExamTabConfig[] = [
  {
    id: 'examination-sessions',
    label: 'Examination Sessions',
    icon: 'Calendar',
    description: 'Academic year examination sessions - regular, supplementary, and special exams',
    fields: [
      {
        key: 'academicYear',
        label: 'Academic Year',
        type: 'text',
        required: true,
        placeholder: '2023-24',
      },
      { key: 'sessionName', label: 'Session Name', type: 'text', required: true },
      {
        key: 'sessionType',
        label: 'Session Type',
        type: 'select',
        required: true,
        options: ['Regular', 'Supplementary', 'Special', 'Re-examination'],
      },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'startDate', label: 'Start Date', type: 'date', required: true },
      { key: 'endDate', label: 'End Date', type: 'date', required: true },
      { key: 'totalCourses', label: 'Total Courses', type: 'number' },
      { key: 'totalStudents', label: 'Total Students Registered', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Scheduled', 'Ongoing', 'Completed', 'Results Published'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        sessionName: 'End Semester Exam - Even Sem',
        sessionType: 'Regular',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        startDate: '2024-05-10',
        endDate: '2024-05-30',
        totalCourses: 6,
        totalStudents: 120,
        status: 'Results Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        sessionName: 'End Semester Exam - Odd Sem',
        sessionType: 'Regular',
        programOffering: 'B.Tech CSE AI R22',
        semester: '3',
        startDate: '2023-12-05',
        endDate: '2023-12-22',
        totalCourses: 7,
        totalStudents: 118,
        status: 'Results Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        sessionName: 'Supplementary Exam - Even Sem',
        sessionType: 'Supplementary',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        startDate: '2024-07-15',
        endDate: '2024-07-25',
        totalCourses: 6,
        totalStudents: 28,
        status: 'Results Published',
        remarks: 'For students with backlogs',
      },
      {
        academicYear: '2024-25',
        sessionName: 'End Semester Exam - Odd Sem',
        sessionType: 'Regular',
        programOffering: 'B.Tech CSE AI R22',
        semester: '5',
        startDate: '2024-12-02',
        endDate: '2024-12-20',
        totalCourses: 6,
        totalStudents: 115,
        status: 'Scheduled',
        remarks: 'Upcoming',
      },
    ],
  },
  {
    id: 'examination-schedule',
    label: 'Examination Schedule',
    icon: 'ClipboardList',
    description: 'Detailed examination timetable with course, date, time, and venue mapping',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'sessionName', label: 'Session', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'examDate', label: 'Exam Date', type: 'date', required: true },
      {
        key: 'examTime',
        label: 'Exam Time',
        type: 'text',
        required: true,
        placeholder: '10:00 AM - 1:00 PM',
      },
      { key: 'duration', label: 'Duration (Hours)', type: 'number', required: true },
      { key: 'venue', label: 'Venue/Hall', type: 'text' },
      { key: 'maxMarks', label: 'Max Marks', type: 'number' },
      { key: 'studentsRegistered', label: 'Students Registered', type: 'number' },
      { key: 'faculty', label: 'Course Faculty', type: 'text' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Scheduled', 'Conducted', 'Postponed', 'Cancelled'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        sessionName: 'End Semester - Even',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        examDate: '2024-05-10',
        examTime: '10:00 AM - 1:00 PM',
        duration: 3,
        venue: 'Hall A1, A2',
        maxMarks: 60,
        studentsRegistered: 120,
        faculty: 'Dr. Anil Kumar',
        status: 'Conducted',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        sessionName: 'End Semester - Even',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        examDate: '2024-05-13',
        examTime: '10:00 AM - 1:00 PM',
        duration: 3,
        venue: 'Hall B1, B2',
        maxMarks: 60,
        studentsRegistered: 120,
        faculty: 'Dr. Priya Sharma',
        status: 'Conducted',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        sessionName: 'End Semester - Even',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS403',
        courseName: 'Computer Networks',
        examDate: '2024-05-16',
        examTime: '2:00 PM - 5:00 PM',
        duration: 3,
        venue: 'Hall A1, A2',
        maxMarks: 60,
        studentsRegistered: 120,
        faculty: 'Prof. Suresh Babu',
        status: 'Conducted',
        remarks: '',
      },
    ],
  },
  {
    id: 'internal-assessment',
    label: 'Internal Assessment',
    icon: 'FileEdit',
    description: 'Internal assessment marks - CIE, assignments, quizzes, and mid-term exams',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text', required: true },
      {
        key: 'assessmentType',
        label: 'Assessment Type',
        type: 'select',
        required: true,
        options: [
          'Mid-Term 1',
          'Mid-Term 2',
          'Quiz',
          'Assignment',
          'Seminar',
          'Lab Internal',
          'Project Review',
        ],
      },
      { key: 'maxMarks', label: 'Max Marks', type: 'number', required: true },
      { key: 'studentsAppeared', label: 'Students Appeared', type: 'number' },
      { key: 'averageMarks', label: 'Average Marks', type: 'number' },
      { key: 'passPercentage', label: 'Pass %', type: 'percentage' },
      { key: 'conductedDate', label: 'Conducted Date', type: 'date' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Marks Entered', 'Verified', 'Published', 'Pending'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        assessmentType: 'Mid-Term 1',
        maxMarks: 20,
        studentsAppeared: 118,
        averageMarks: 14,
        passPercentage: 88,
        conductedDate: '2024-02-15',
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        assessmentType: 'Mid-Term 2',
        maxMarks: 20,
        studentsAppeared: 116,
        averageMarks: 15,
        passPercentage: 91,
        conductedDate: '2024-04-10',
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        assessmentType: 'Mid-Term 1',
        maxMarks: 20,
        studentsAppeared: 120,
        averageMarks: 13,
        passPercentage: 85,
        conductedDate: '2024-02-18',
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS403',
        courseName: 'Computer Networks',
        faculty: 'Prof. Suresh Babu',
        assessmentType: 'Assignment',
        maxMarks: 10,
        studentsAppeared: 120,
        averageMarks: 8,
        passPercentage: 95,
        conductedDate: '2024-03-01',
        status: 'Verified',
        remarks: 'Online submission',
      },
    ],
  },
  {
    id: 'end-semester-examination',
    label: 'End Semester Examination',
    icon: 'BookOpen',
    description: 'End semester examination records with marks, attendance, and malpractice cases',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text', required: true },
      { key: 'examDate', label: 'Exam Date', type: 'date', required: true },
      { key: 'maxMarks', label: 'Max External Marks', type: 'number', required: true },
      { key: 'studentsRegistered', label: 'Students Registered', type: 'number' },
      { key: 'studentsAppeared', label: 'Students Appeared', type: 'number' },
      { key: 'studentsAbsent', label: 'Students Absent', type: 'number' },
      { key: 'averageMarks', label: 'Average Marks', type: 'number' },
      { key: 'passPercentage', label: 'Pass %', type: 'percentage' },
      { key: 'malpracticeCases', label: 'Malpractice Cases', type: 'number' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Conducted', 'Evaluation Done', 'Results Published', 'Under Review'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        examDate: '2024-05-10',
        maxMarks: 60,
        studentsRegistered: 120,
        studentsAppeared: 118,
        studentsAbsent: 2,
        averageMarks: 42,
        passPercentage: 85,
        malpracticeCases: 0,
        status: 'Results Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        examDate: '2024-05-13',
        maxMarks: 60,
        studentsRegistered: 120,
        studentsAppeared: 119,
        studentsAbsent: 1,
        averageMarks: 38,
        passPercentage: 80,
        malpracticeCases: 1,
        status: 'Results Published',
        remarks: '1 malpractice case referred to committee',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS403',
        courseName: 'Computer Networks',
        faculty: 'Prof. Suresh Babu',
        examDate: '2024-05-16',
        maxMarks: 60,
        studentsRegistered: 120,
        studentsAppeared: 117,
        studentsAbsent: 3,
        averageMarks: 40,
        passPercentage: 82,
        malpracticeCases: 0,
        status: 'Results Published',
        remarks: '',
      },
    ],
  },
  {
    id: 'student-results',
    label: 'Student Results',
    icon: 'Users',
    description: 'Individual student results with internal + external marks and grade calculation',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text' },
      { key: 'internalMarks', label: 'Internal Marks', type: 'number', required: true },
      { key: 'externalMarks', label: 'External Marks', type: 'number', required: true },
      { key: 'totalMarks', label: 'Total Marks', type: 'number' },
      { key: 'grade', label: 'Grade', type: 'text' },
      { key: 'gradePoint', label: 'Grade Point', type: 'number' },
      { key: 'credits', label: 'Credits', type: 'number' },
      {
        key: 'result',
        label: 'Result',
        type: 'select',
        options: ['Pass', 'Fail', 'Absent', 'Withheld'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022001',
        studentName: 'Rahul Verma',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        internalMarks: 36,
        externalMarks: 52,
        totalMarks: 88,
        grade: 'O',
        gradePoint: 10,
        credits: 4,
        result: 'Pass',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022002',
        studentName: 'Priya Sharma',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        internalMarks: 34,
        externalMarks: 48,
        totalMarks: 82,
        grade: 'A+',
        gradePoint: 9,
        credits: 4,
        result: 'Pass',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022003',
        studentName: 'Karthik Raja',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        internalMarks: 18,
        externalMarks: 22,
        totalMarks: 40,
        grade: 'F',
        gradePoint: 0,
        credits: 4,
        result: 'Fail',
        remarks: 'Below passing marks',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022001',
        studentName: 'Rahul Verma',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        internalMarks: 32,
        externalMarks: 45,
        totalMarks: 77,
        grade: 'A',
        gradePoint: 8,
        credits: 4,
        result: 'Pass',
        remarks: '',
      },
    ],
  },
  {
    id: 'subject-wise-results',
    label: 'Subject-wise Results',
    icon: 'BarChart3',
    description: 'Consolidated subject-wise result analysis with pass/fail statistics',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text', required: true },
      { key: 'studentsAppeared', label: 'Students Appeared', type: 'number', required: true },
      { key: 'studentsPassed', label: 'Students Passed', type: 'number', required: true },
      { key: 'studentsFailed', label: 'Students Failed', type: 'number' },
      { key: 'passPercentage', label: 'Pass %', type: 'percentage', required: true },
      { key: 'averageMarks', label: 'Average Marks', type: 'number' },
      { key: 'highestMarks', label: 'Highest Marks', type: 'number' },
      { key: 'lowestMarks', label: 'Lowest Marks', type: 'number' },
      {
        key: 'gradeDistribution',
        label: 'Grade Distribution',
        type: 'text',
        placeholder: 'O:5, A+:15, A:30, B+:40, B:20, C:8, F:2',
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Published', 'Under Review', 'Pending'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        studentsAppeared: 118,
        studentsPassed: 100,
        studentsFailed: 18,
        passPercentage: 85,
        averageMarks: 42,
        highestMarks: 58,
        lowestMarks: 12,
        gradeDistribution: 'O:8, A+:20, A:30, B+:25, B:12, C:5, F:18',
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        studentsAppeared: 119,
        studentsPassed: 95,
        studentsFailed: 24,
        passPercentage: 80,
        averageMarks: 38,
        highestMarks: 55,
        lowestMarks: 8,
        gradeDistribution: 'O:5, A+:15, A:25, B+:28, B:15, C:7, F:24',
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS403',
        courseName: 'Computer Networks',
        faculty: 'Prof. Suresh Babu',
        studentsAppeared: 117,
        studentsPassed: 96,
        studentsFailed: 21,
        passPercentage: 82,
        averageMarks: 40,
        highestMarks: 56,
        lowestMarks: 10,
        gradeDistribution: 'O:6, A+:18, A:28, B+:26, B:14, C:4, F:21',
        status: 'Published',
        remarks: '',
      },
    ],
  },
  {
    id: 'semester-results',
    label: 'Semester Results',
    icon: 'GraduationCap',
    description: 'Consolidated semester-wise SGPA/CGPA results for each student',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      {
        key: 'totalCreditsRegistered',
        label: 'Credits Registered',
        type: 'number',
        required: true,
      },
      { key: 'totalCreditsEarned', label: 'Credits Earned', type: 'number', required: true },
      { key: 'sgpa', label: 'SGPA', type: 'number', required: true },
      { key: 'cgpa', label: 'CGPA', type: 'number', required: true },
      { key: 'totalBacklogs', label: 'Total Backlogs', type: 'number' },
      {
        key: 'semesterResult',
        label: 'Semester Result',
        type: 'select',
        options: ['Pass', 'Fail', 'Detained', 'Withheld'],
      },
      { key: 'rank', label: 'Rank', type: 'number' },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022001',
        studentName: 'Rahul Verma',
        totalCreditsRegistered: 22,
        totalCreditsEarned: 22,
        sgpa: 9.2,
        cgpa: 9.1,
        totalBacklogs: 0,
        semesterResult: 'Pass',
        rank: 3,
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022002',
        studentName: 'Priya Sharma',
        totalCreditsRegistered: 22,
        totalCreditsEarned: 22,
        sgpa: 9.5,
        cgpa: 9.4,
        totalBacklogs: 0,
        semesterResult: 'Pass',
        rank: 1,
        remarks: 'Topper',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022003',
        studentName: 'Karthik Raja',
        totalCreditsRegistered: 22,
        totalCreditsEarned: 18,
        sgpa: 5.8,
        cgpa: 6.2,
        totalBacklogs: 1,
        semesterResult: 'Fail',
        rank: 0,
        remarks: '1 backlog in CS401',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        registrationNo: 'CS2022004',
        studentName: 'Sneha Gupta',
        totalCreditsRegistered: 22,
        totalCreditsEarned: 22,
        sgpa: 9.3,
        cgpa: 9.2,
        totalBacklogs: 0,
        semesterResult: 'Pass',
        rank: 2,
        remarks: '',
      },
    ],
  },
  {
    id: 'backlog-repository',
    label: 'Backlog Repository',
    icon: 'AlertTriangle',
    description: 'Student backlog records, supplementary exam attempts, and clearance tracking',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Original Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text' },
      { key: 'attemptNumber', label: 'Attempt Number', type: 'number', required: true },
      { key: 'examSession', label: 'Exam Session', type: 'text' },
      { key: 'marksObtained', label: 'Marks Obtained', type: 'number' },
      { key: 'maxMarks', label: 'Max Marks', type: 'number' },
      {
        key: 'result',
        label: 'Result',
        type: 'select',
        options: ['Cleared', 'Not Cleared', 'Absent', 'Pending'],
      },
      { key: 'clearedDate', label: 'Cleared Date', type: 'date' },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2022003',
        studentName: 'Karthik Raja',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        attemptNumber: 2,
        examSession: 'Supplementary Jul 2024',
        marksObtained: 35,
        maxMarks: 60,
        result: 'Cleared',
        clearedDate: '2024-08-10',
        remarks: 'Cleared in supplementary',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2022010',
        studentName: 'Amit Shah',
        semester: '3',
        courseCode: 'CS301',
        courseName: 'Data Structures',
        faculty: 'Dr. Venkat Reddy',
        attemptNumber: 3,
        examSession: 'Supplementary Jul 2024',
        marksObtained: 28,
        maxMarks: 60,
        result: 'Not Cleared',
        clearedDate: '',
        remarks: 'Still pending',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2022015',
        studentName: 'Ravi Kumar',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        attemptNumber: 2,
        examSession: 'Supplementary Jul 2024',
        marksObtained: 32,
        maxMarks: 60,
        result: 'Cleared',
        clearedDate: '2024-08-10',
        remarks: '',
      },
    ],
  },
  {
    id: 'academic-achievements',
    label: 'Academic Achievements',
    icon: 'Trophy',
    description: 'University ranks, gold medals, and academic awards for students',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      {
        key: 'achievementType',
        label: 'Achievement Type',
        type: 'select',
        required: true,
        options: [
          'University Rank',
          'Gold Medal',
          'Academic Award',
          'Merit Scholarship',
          'Best Outgoing Student',
        ],
      },
      { key: 'rank', label: 'Rank/Position', type: 'text' },
      { key: 'cgpa', label: 'CGPA', type: 'number' },
      { key: 'awardName', label: 'Award/Medal Name', type: 'text' },
      { key: 'awardedBy', label: 'Awarded By', type: 'text' },
      { key: 'convocationYear', label: 'Convocation Year', type: 'text' },
      { key: 'prizeAmount', label: 'Prize Amount (₹)', type: 'currency' },
      {
        key: 'evidenceAvailable',
        label: 'Evidence Available',
        type: 'select',
        options: ['Yes', 'No'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2020001',
        studentName: 'Kavya Reddy',
        achievementType: 'University Rank',
        rank: '1st Rank',
        cgpa: 9.85,
        awardName: 'University Gold Medal',
        awardedBy: 'Anna University',
        convocationYear: '2024',
        prizeAmount: 50000,
        evidenceAvailable: 'Yes',
        remarks: 'Highest CGPA in university',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2020005',
        studentName: 'Arun Menon',
        achievementType: 'Gold Medal',
        rank: '2nd Rank',
        cgpa: 9.72,
        awardName: 'College Gold Medal',
        awardedBy: 'SVCE',
        convocationYear: '2024',
        prizeAmount: 25000,
        evidenceAvailable: 'Yes',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech ECE VLSI R22',
        registrationNo: 'EC2020012',
        studentName: 'Meera Patel',
        achievementType: 'University Rank',
        rank: '3rd Rank',
        cgpa: 9.68,
        awardName: 'University Bronze Medal',
        awardedBy: 'Anna University',
        convocationYear: '2024',
        prizeAmount: 15000,
        evidenceAvailable: 'Yes',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        registrationNo: 'CS2020010',
        studentName: 'Rohan Desai',
        achievementType: 'Best Outgoing Student',
        rank: '',
        cgpa: 9.45,
        awardName: 'Best Outgoing Student Award',
        awardedBy: 'SVCE Alumni Association',
        convocationYear: '2024',
        prizeAmount: 10000,
        evidenceAvailable: 'Yes',
        remarks: 'Academic + Extra-curricular excellence',
      },
    ],
  },
  {
    id: 'co-attainment-input',
    label: 'CO Attainment Input',
    icon: 'Target',
    description:
      'Marks and assessment data for CO attainment. Calculations performed by future OBE Module.',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'courseCode', label: 'Course Code', type: 'text', required: true },
      { key: 'courseName', label: 'Course Name', type: 'text', required: true },
      { key: 'faculty', label: 'Faculty', type: 'text', required: true },
      {
        key: 'assessmentTool',
        label: 'Assessment Tool',
        type: 'select',
        required: true,
        options: [
          'Mid-Term 1',
          'Mid-Term 2',
          'End Semester',
          'Assignment',
          'Quiz',
          'Lab Exam',
          'Project',
        ],
      },
      {
        key: 'coMapped',
        label: 'CO Mapped',
        type: 'text',
        required: true,
        placeholder: 'CO1, CO2, CO3',
      },
      { key: 'questionNumber', label: 'Question/Component', type: 'text' },
      { key: 'maxMarks', label: 'Max Marks', type: 'number', required: true },
      { key: 'studentsAboveThreshold', label: 'Students Above Threshold', type: 'number' },
      { key: 'totalStudents', label: 'Total Students', type: 'number' },
      { key: 'threshold', label: 'Threshold %', type: 'percentage' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Data Entered', 'Verified', 'Sent to OBE', 'Pending'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        assessmentTool: 'Mid-Term 1',
        coMapped: 'CO1, CO2',
        questionNumber: 'Q1-Q5',
        maxMarks: 20,
        studentsAboveThreshold: 95,
        totalStudents: 118,
        threshold: 60,
        status: 'Verified',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS401',
        courseName: 'Machine Learning',
        faculty: 'Dr. Anil Kumar',
        assessmentTool: 'End Semester',
        coMapped: 'CO1, CO2, CO3, CO4, CO5',
        questionNumber: 'Full Paper',
        maxMarks: 60,
        studentsAboveThreshold: 88,
        totalStudents: 118,
        threshold: 60,
        status: 'Verified',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        courseCode: 'CS402',
        courseName: 'Database Systems',
        faculty: 'Dr. Priya Sharma',
        assessmentTool: 'Mid-Term 1',
        coMapped: 'CO1, CO2',
        questionNumber: 'Q1-Q4',
        maxMarks: 20,
        studentsAboveThreshold: 90,
        totalStudents: 120,
        threshold: 60,
        status: 'Data Entered',
        remarks: '',
      },
    ],
  },
  {
    id: 'result-analytics',
    label: 'Result Analytics',
    icon: 'PieChart',
    description: 'Result analysis reports - batch-wise, department-wise, and trend analysis',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'programOffering', label: 'Program Offering', type: 'text', required: true },
      {
        key: 'semester',
        label: 'Semester',
        type: 'select',
        required: true,
        options: ['1', '2', '3', '4', '5', '6', '7', '8'],
      },
      { key: 'batchSize', label: 'Batch Size', type: 'number', required: true },
      { key: 'studentsAppeared', label: 'Students Appeared', type: 'number', required: true },
      { key: 'passPercentage', label: 'Overall Pass %', type: 'percentage', required: true },
      { key: 'averageSGPA', label: 'Average SGPA', type: 'number' },
      { key: 'topperSGPA', label: 'Topper SGPA', type: 'number' },
      { key: 'distinction', label: 'Distinction (>8.5)', type: 'number' },
      { key: 'firstClass', label: 'First Class (7-8.5)', type: 'number' },
      { key: 'secondClass', label: 'Second Class (5.5-7)', type: 'number' },
      { key: 'failed', label: 'Failed (<5.5)', type: 'number' },
      { key: 'detained', label: 'Detained', type: 'number' },
      { key: 'improvementOverPrevSem', label: 'Improvement Over Prev Sem %', type: 'percentage' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Published', 'Draft', 'Under Review'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech CSE AI R22',
        semester: '4',
        batchSize: 120,
        studentsAppeared: 118,
        passPercentage: 85,
        averageSGPA: 7.8,
        topperSGPA: 9.5,
        distinction: 35,
        firstClass: 45,
        secondClass: 20,
        failed: 18,
        detained: 2,
        improvementOverPrevSem: 3,
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech ECE VLSI R22',
        semester: '4',
        batchSize: 120,
        studentsAppeared: 115,
        passPercentage: 82,
        averageSGPA: 7.5,
        topperSGPA: 9.3,
        distinction: 28,
        firstClass: 42,
        secondClass: 25,
        failed: 20,
        detained: 5,
        improvementOverPrevSem: 2,
        status: 'Published',
        remarks: '',
      },
      {
        academicYear: '2023-24',
        programOffering: 'B.Tech MECH Robotics R22',
        semester: '4',
        batchSize: 120,
        studentsAppeared: 110,
        passPercentage: 78,
        averageSGPA: 7.2,
        topperSGPA: 9.1,
        distinction: 22,
        firstClass: 38,
        secondClass: 28,
        failed: 22,
        detained: 10,
        improvementOverPrevSem: -1,
        status: 'Published',
        remarks: 'Slight decline from previous semester',
      },
    ],
  },
];

export const examDocumentCategories = [
  { id: 'exam-notifications', label: 'Examination Notifications & Circulars', count: 35 },
  { id: 'exam-schedules', label: 'Examination Schedules & Timetables', count: 24 },
  { id: 'question-papers', label: 'Question Papers (Previous Years)', count: 150 },
  { id: 'answer-keys', label: 'Answer Keys & Marking Schemes', count: 80 },
  { id: 'result-sheets', label: 'Result Sheets & Grade Cards', count: 45 },
  { id: 'revaluation-records', label: 'Revaluation & Challenge Records', count: 18 },
  { id: 'malpractice-records', label: 'Malpractice Case Records', count: 8 },
  { id: 'convocation-records', label: 'Convocation & Degree Records', count: 12 },
  { id: 'co-attainment-data', label: 'CO Attainment Data Sheets', count: 60 },
  { id: 'analytics-reports', label: 'Result Analytics Reports', count: 20 },
  { id: 'audit-reports', label: 'Examination Audit Reports', count: 6 },
  { id: 'compliance-docs', label: 'NAAC/NBA Examination Evidence', count: 25 },
];
