export interface TPOFieldConfig {
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'select' | 'currency' | 'percentage';
  required?: boolean;
  options?: string[];
  placeholder?: string;
}

export interface TPOTabConfig {
  id: string;
  label: string;
  icon: string;
  description: string;
  fields: TPOFieldConfig[];
  sampleData: Record<string, string | number>[];
}

export const tpoTabConfigs: TPOTabConfig[] = [
  {
    id: 'recruiters',
    label: 'Recruiters',
    icon: 'Building2',
    description: 'Registered recruiters and company partnerships for campus placements',
    fields: [
      { key: 'companyName', label: 'Company Name', type: 'text', required: true },
      { key: 'logo', label: 'Logo URL', type: 'text', placeholder: 'https://company.com/logo.png' },
      {
        key: 'companyWebsite',
        label: 'Company Website',
        type: 'text',
        placeholder: 'https://company.com',
      },
      {
        key: 'industry',
        label: 'Industry',
        type: 'select',
        required: true,
        options: [
          'IT/Software',
          'Manufacturing',
          'Banking & Finance',
          'Consulting',
          'Healthcare',
          'E-commerce',
          'Automotive',
          'Telecom',
          'FMCG',
          'Energy',
          'Education',
          'Government/PSU',
          'Startup',
          'Other',
        ],
      },
      { key: 'contactPerson', label: 'Contact Person', type: 'text', required: true },
      { key: 'designation', label: 'Designation', type: 'text' },
      { key: 'email', label: 'Email', type: 'text' },
      { key: 'phone', label: 'Phone', type: 'text' },
      { key: 'location', label: 'Location', type: 'text' },
      { key: 'packageOffered', label: 'Avg. Package (LPA)', type: 'currency' },
      { key: 'recruitingSince', label: 'Recruiting Since', type: 'text' },
      { key: 'studentsHired', label: 'Students Hired (Total)', type: 'number' },
      {
        key: 'mouAvailable',
        label: 'MoU Available',
        type: 'select',
        options: ['Yes', 'No', 'In Progress'],
      },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        companyName: 'TCS',
        logo: 'https://logo.clearbit.com/tcs.com',
        companyWebsite: 'https://www.tcs.com',
        industry: 'IT/Software',
        contactPerson: 'Ramesh Iyer',
        designation: 'HR Manager',
        email: 'ramesh.iyer@tcs.com',
        phone: '9876543210',
        location: 'Mumbai',
        packageOffered: 7.5,
        recruitingSince: '2015',
        studentsHired: 145,
        mouAvailable: 'Yes',
        status: 'Active',
        remarks: 'Tier-1 recruiter',
      },
      {
        companyName: 'Infosys',
        logo: 'https://logo.clearbit.com/infosys.com',
        companyWebsite: 'https://www.infosys.com',
        industry: 'IT/Software',
        contactPerson: 'Sneha Reddy',
        designation: 'Campus Lead',
        email: 'sneha.r@infosys.com',
        phone: '9876543211',
        location: 'Bangalore',
        packageOffered: 6.8,
        recruitingSince: '2016',
        studentsHired: 120,
        mouAvailable: 'Yes',
        status: 'Active',
        remarks: 'Regular recruiter',
      },
      {
        companyName: 'Deloitte',
        logo: 'https://logo.clearbit.com/deloitte.com',
        companyWebsite: 'https://www.deloitte.com',
        industry: 'Consulting',
        contactPerson: 'Amit Joshi',
        designation: 'Recruitment Head',
        email: 'amit.j@deloitte.com',
        phone: '9876543212',
        location: 'Hyderabad',
        packageOffered: 12.5,
        recruitingSince: '2018',
        studentsHired: 35,
        mouAvailable: 'Yes',
        status: 'Active',
        remarks: 'Premium recruiter',
      },
      {
        companyName: 'HDFC Bank',
        logo: 'https://logo.clearbit.com/hdfcbank.com',
        companyWebsite: 'https://www.hdfcbank.com',
        industry: 'Banking & Finance',
        contactPerson: 'Priya Nair',
        designation: 'VP - HR',
        email: 'priya.n@hdfc.com',
        phone: '9876543213',
        location: 'Mumbai',
        packageOffered: 8.2,
        recruitingSince: '2017',
        studentsHired: 60,
        mouAvailable: 'In Progress',
        status: 'Active',
        remarks: 'Finance roles',
      },
    ],
  },
  {
    id: 'placement-offers',
    label: 'Placement Offers',
    icon: 'Briefcase',
    description: 'Campus placement offers, packages, and student selections',
    fields: [
      {
        key: 'offerId',
        label: 'Offer ID',
        type: 'text',
        required: true,
        placeholder: 'PO-2024-001',
      },
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'company', label: 'Company', type: 'text', required: true },
      { key: 'role', label: 'Job Role', type: 'text', required: true },
      { key: 'packageLPA', label: 'Package (LPA)', type: 'currency', required: true },
      { key: 'offerDate', label: 'Offer Date', type: 'date' },
      { key: 'joiningDate', label: 'Joining Date', type: 'date' },
      { key: 'location', label: 'Job Location', type: 'text' },
      {
        key: 'offerType',
        label: 'Offer Type',
        type: 'select',
        options: ['On-Campus', 'Off-Campus', 'Pool Campus', 'PPO'],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Offered', 'Accepted', 'Declined', 'Joined', 'Deferred'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        offerId: 'PO-2024-001',
        studentName: 'Arun Kumar',
        registrationNo: 'CS2021001',
        department: 'Computer Science',
        company: 'TCS',
        role: 'Software Engineer',
        packageLPA: 7.5,
        offerDate: '2024-12-15',
        joiningDate: '2025-07-01',
        location: 'Chennai',
        offerType: 'On-Campus',
        status: 'Accepted',
        remarks: '',
      },
      {
        offerId: 'PO-2024-002',
        studentName: 'Meera Patel',
        registrationNo: 'EC2021045',
        department: 'Electronics',
        company: 'Deloitte',
        role: 'Business Analyst',
        packageLPA: 12.5,
        offerDate: '2024-11-20',
        joiningDate: '2025-06-15',
        location: 'Hyderabad',
        offerType: 'On-Campus',
        status: 'Joined',
        remarks: 'Highest package ECE',
      },
      {
        offerId: 'PO-2024-003',
        studentName: 'Rahul Singh',
        registrationNo: 'ME2021023',
        department: 'Mechanical',
        company: 'Tata Motors',
        role: 'Graduate Engineer',
        packageLPA: 6.2,
        offerDate: '2025-01-10',
        joiningDate: '2025-07-15',
        location: 'Pune',
        offerType: 'On-Campus',
        status: 'Offered',
        remarks: '',
      },
      {
        offerId: 'PO-2024-004',
        studentName: 'Divya Sharma',
        registrationNo: 'CS2021078',
        department: 'Computer Science',
        company: 'Google',
        role: 'SDE-1',
        packageLPA: 32.0,
        offerDate: '2024-10-05',
        joiningDate: '2025-08-01',
        location: 'Bangalore',
        offerType: 'On-Campus',
        status: 'Accepted',
        remarks: 'Dream company placement',
      },
    ],
  },
  {
    id: 'internships',
    label: 'Internships',
    icon: 'UserCheck',
    description: 'Student internship records, stipends, and completion status',
    fields: [
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'company', label: 'Company/Organization', type: 'text', required: true },
      { key: 'internshipTitle', label: 'Internship Title', type: 'text', required: true },
      {
        key: 'internshipType',
        label: 'Internship Type',
        type: 'select',
        required: true,
        options: ['Part Time', 'Full Time'],
      },
      {
        key: 'workMode',
        label: 'Work Mode',
        type: 'select',
        options: ['Onsite', 'Remote', 'Hybrid'],
      },
      { key: 'duration', label: 'Duration', type: 'text' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'stipend', label: 'Monthly Stipend (₹)', type: 'currency' },
      {
        key: 'internshipCategory',
        label: 'Category',
        type: 'select',
        options: [
          'Summer Internship',
          'Winter Internship',
          'Semester Internship',
          'Industry Project',
          'Research Internship',
          'Virtual Internship',
        ],
      },
      {
        key: 'convertedToFTE',
        label: 'Converted to FTE',
        type: 'select',
        options: ['Yes', 'No', 'Pending'],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Ongoing', 'Completed', 'Terminated', 'Extended'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        studentName: 'Karthik Rajan',
        registrationNo: 'CS2022015',
        department: 'Computer Science',
        company: 'Microsoft',
        internshipTitle: 'Software Engineering Intern',
        internshipType: 'Full Time',
        workMode: 'Hybrid',
        duration: '3 months',
        startDate: '2024-05-15',
        endDate: '2024-08-15',
        stipend: 80000,
        internshipCategory: 'Summer Internship',
        convertedToFTE: 'Yes',
        status: 'Completed',
        remarks: 'PPO received',
      },
      {
        studentName: 'Ananya Gupta',
        registrationNo: 'IT2022034',
        department: 'Information Technology',
        company: 'Amazon',
        internshipTitle: 'Data Science Intern',
        internshipType: 'Full Time',
        workMode: 'Onsite',
        duration: '6 months',
        startDate: '2024-01-10',
        endDate: '2024-06-30',
        stipend: 60000,
        internshipCategory: 'Semester Internship',
        convertedToFTE: 'Pending',
        status: 'Completed',
        remarks: 'Excellent performance',
      },
      {
        studentName: 'Suresh Babu',
        registrationNo: 'ME2022008',
        department: 'Mechanical',
        company: 'Bosch',
        internshipTitle: 'Design Engineering Intern',
        internshipType: 'Full Time',
        workMode: 'Onsite',
        duration: '2 months',
        startDate: '2024-06-01',
        endDate: '2024-07-31',
        stipend: 25000,
        internshipCategory: 'Summer Internship',
        convertedToFTE: 'No',
        status: 'Completed',
        remarks: '',
      },
      {
        studentName: 'Preethi Nair',
        registrationNo: 'EC2022056',
        department: 'Electronics',
        company: 'Texas Instruments',
        internshipTitle: 'VLSI Design Intern',
        internshipType: 'Part Time',
        workMode: 'Remote',
        duration: '4 months',
        startDate: '2024-05-01',
        endDate: '2024-08-31',
        stipend: 45000,
        internshipCategory: 'Summer Internship',
        convertedToFTE: 'Yes',
        status: 'Completed',
        remarks: 'Converted to full-time',
      },
    ],
  },
  {
    id: 'higher-education',
    label: 'Higher Education',
    icon: 'BookOpen',
    description: 'Students pursuing higher education, competitive exams, and admissions',
    fields: [
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      {
        key: 'programPursued',
        label: 'Program Pursued',
        type: 'select',
        required: true,
        options: ['M.Tech', 'M.S.', 'MBA', 'M.Sc', 'Ph.D.', 'M.E.', 'MCA', 'Other PG'],
      },
      { key: 'university', label: 'University/Institution', type: 'text', required: true },
      { key: 'country', label: 'Country', type: 'text' },
      {
        key: 'entranceExam',
        label: 'Entrance Exam',
        type: 'select',
        options: [
          'GATE',
          'GRE',
          'GMAT',
          'CAT',
          'JAM',
          'TOEFL',
          'IELTS',
          'NET',
          'State CET',
          'University Exam',
          'N/A',
        ],
      },
      { key: 'examScore', label: 'Exam Score/Rank', type: 'text' },
      { key: 'yearOfAdmission', label: 'Year of Admission', type: 'text' },
      {
        key: 'scholarshipReceived',
        label: 'Scholarship Received',
        type: 'select',
        options: ['Yes', 'No'],
      },
      { key: 'scholarshipDetails', label: 'Scholarship Details', type: 'text' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Admitted', 'Pursuing', 'Completed', 'Deferred', 'Applied'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        studentName: 'Rohan Desai',
        registrationNo: 'CS2020045',
        department: 'Computer Science',
        programPursued: 'M.S.',
        university: 'Stanford University',
        country: 'USA',
        entranceExam: 'GRE',
        examScore: '328/340',
        yearOfAdmission: '2024',
        scholarshipReceived: 'Yes',
        scholarshipDetails: 'Full tuition waiver + RA',
        status: 'Pursuing',
        remarks: 'AI/ML specialization',
      },
      {
        studentName: 'Sneha Kulkarni',
        registrationNo: 'EC2020012',
        department: 'Electronics',
        programPursued: 'M.Tech',
        university: 'IIT Bombay',
        country: 'India',
        entranceExam: 'GATE',
        examScore: 'AIR 156',
        yearOfAdmission: '2024',
        scholarshipReceived: 'Yes',
        scholarshipDetails: 'MHRD Fellowship',
        status: 'Pursuing',
        remarks: 'VLSI Design',
      },
      {
        studentName: 'Aditya Verma',
        registrationNo: 'ME2020078',
        department: 'Mechanical',
        programPursued: 'MBA',
        university: 'IIM Ahmedabad',
        country: 'India',
        entranceExam: 'CAT',
        examScore: '99.2 percentile',
        yearOfAdmission: '2024',
        scholarshipReceived: 'No',
        scholarshipDetails: '',
        status: 'Pursuing',
        remarks: 'Operations Management',
      },
      {
        studentName: 'Lakshmi Iyer',
        registrationNo: 'CS2020034',
        department: 'Computer Science',
        programPursued: 'Ph.D.',
        university: 'MIT',
        country: 'USA',
        entranceExam: 'GRE',
        examScore: '332/340',
        yearOfAdmission: '2024',
        scholarshipReceived: 'Yes',
        scholarshipDetails: 'Full fellowship',
        status: 'Pursuing',
        remarks: 'NLP research',
      },
    ],
  },
  {
    id: 'entrepreneurship-startups',
    label: 'Entrepreneurship & Startups',
    icon: 'Rocket',
    description: 'Student and alumni startups, incubation, and entrepreneurship initiatives',
    fields: [
      { key: 'startupName', label: 'Startup Name', type: 'text', required: true },
      { key: 'founderName', label: 'Founder Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      {
        key: 'domain',
        label: 'Domain',
        type: 'select',
        options: [
          'EdTech',
          'HealthTech',
          'FinTech',
          'AgriTech',
          'E-commerce',
          'SaaS',
          'AI/ML',
          'IoT',
          'CleanTech',
          'Social Enterprise',
          'Manufacturing',
          'Other',
        ],
      },
      { key: 'foundedYear', label: 'Founded Year', type: 'text' },
      { key: 'incubationCenter', label: 'Incubation Center', type: 'text' },
      { key: 'fundingReceived', label: 'Funding Received (₹)', type: 'currency' },
      {
        key: 'fundingStage',
        label: 'Funding Stage',
        type: 'select',
        options: [
          'Bootstrapped',
          'Pre-Seed',
          'Seed',
          'Series A',
          'Series B',
          'Grant Funded',
          'Revenue Generating',
        ],
      },
      { key: 'teamSize', label: 'Team Size', type: 'number' },
      { key: 'revenue', label: 'Annual Revenue (₹)', type: 'currency' },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Ideation', 'MVP', 'Early Stage', 'Growth', 'Established', 'Acquired', 'Closed'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        startupName: 'EduLearn AI',
        founderName: 'Arjun Menon',
        registrationNo: 'CS2019056',
        department: 'Computer Science',
        domain: 'EdTech',
        foundedYear: '2023',
        incubationCenter: 'University Innovation Hub',
        fundingReceived: 2500000,
        fundingStage: 'Seed',
        teamSize: 8,
        revenue: 1200000,
        status: 'Growth',
        remarks: 'AI-powered learning platform',
      },
      {
        startupName: 'FarmConnect',
        founderName: 'Kavitha Reddy',
        registrationNo: 'IT2019023',
        department: 'Information Technology',
        domain: 'AgriTech',
        foundedYear: '2022',
        incubationCenter: 'State Startup Hub',
        fundingReceived: 5000000,
        fundingStage: 'Series A',
        teamSize: 15,
        revenue: 8000000,
        status: 'Growth',
        remarks: 'Farm-to-consumer marketplace',
      },
      {
        startupName: 'MediTrack',
        founderName: 'Dr. Sanjay Rao',
        registrationNo: 'EC2018045',
        department: 'Electronics',
        domain: 'HealthTech',
        foundedYear: '2021',
        incubationCenter: 'University Innovation Hub',
        fundingReceived: 1000000,
        fundingStage: 'Pre-Seed',
        teamSize: 5,
        revenue: 500000,
        status: 'Early Stage',
        remarks: 'IoT health monitoring',
      },
      {
        startupName: 'GreenVolt',
        founderName: 'Nikhil Sharma',
        registrationNo: 'EE2019012',
        department: 'Electrical',
        domain: 'CleanTech',
        foundedYear: '2023',
        incubationCenter: 'NASSCOM Incubator',
        fundingReceived: 3500000,
        fundingStage: 'Seed',
        teamSize: 6,
        revenue: 0,
        status: 'MVP',
        remarks: 'Solar energy solutions',
      },
    ],
  },
  {
    id: 'training-activities',
    label: 'Training Activities',
    icon: 'Presentation',
    description: 'Training programs, workshops, and skill development activities',
    fields: [
      { key: 'programName', label: 'Program Name', type: 'text', required: true },
      {
        key: 'trainingType',
        label: 'Training Type',
        type: 'select',
        required: true,
        options: [
          'Aptitude Training',
          'Technical Training',
          'Soft Skills',
          'Communication',
          'Mock Interviews',
          'Group Discussion',
          'Resume Building',
          'Industry Workshop',
          'Certification Course',
          'Hackathon',
          'Coding Bootcamp',
          'Personality Development',
        ],
      },
      { key: 'trainer', label: 'Trainer/Organization', type: 'text', required: true },
      { key: 'department', label: 'Target Department', type: 'text' },
      { key: 'startDate', label: 'Start Date', type: 'date' },
      { key: 'endDate', label: 'End Date', type: 'date' },
      { key: 'duration', label: 'Duration (Hours)', type: 'number' },
      { key: 'participants', label: 'No. of Participants', type: 'number' },
      { key: 'studentsAttended', label: 'No. Students Attended', type: 'number' },
      { key: 'cost', label: 'Cost (₹)', type: 'currency' },
      { key: 'feedbackScore', label: 'Feedback Score (/5)', type: 'number' },
      {
        key: 'certificationProvided',
        label: 'Certification',
        type: 'select',
        options: ['Yes', 'No'],
      },
      {
        key: 'status',
        label: 'Status',
        type: 'select',
        options: ['Planned', 'Ongoing', 'Completed', 'Cancelled'],
      },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      {
        programName: 'Aptitude & Reasoning Bootcamp',
        trainingType: 'Aptitude Training',
        trainer: 'Career Launcher',
        department: 'All Departments',
        startDate: '2024-07-01',
        endDate: '2024-08-15',
        duration: 60,
        participants: 450,
        studentsAttended: 420,
        cost: 500000,
        feedbackScore: 4.2,
        certificationProvided: 'Yes',
        status: 'Completed',
        remarks: 'Pre-placement training',
      },
      {
        programName: 'Full Stack Web Development',
        trainingType: 'Technical Training',
        trainer: 'Coding Ninjas',
        department: 'CS & IT',
        startDate: '2024-06-15',
        endDate: '2024-09-15',
        duration: 120,
        participants: 180,
        studentsAttended: 165,
        cost: 800000,
        feedbackScore: 4.5,
        certificationProvided: 'Yes',
        status: 'Completed',
        remarks: 'MERN stack',
      },
      {
        programName: 'Corporate Communication Skills',
        trainingType: 'Soft Skills',
        trainer: 'Dale Carnegie India',
        department: 'All Departments',
        startDate: '2024-08-01',
        endDate: '2024-08-30',
        duration: 30,
        participants: 300,
        studentsAttended: 275,
        cost: 350000,
        feedbackScore: 4.0,
        certificationProvided: 'No',
        status: 'Completed',
        remarks: 'Interview preparation',
      },
      {
        programName: 'AWS Cloud Practitioner',
        trainingType: 'Certification Course',
        trainer: 'AWS Academy',
        department: 'CS & IT & EC',
        startDate: '2024-09-01',
        endDate: '2024-11-30',
        duration: 80,
        participants: 120,
        studentsAttended: 112,
        cost: 600000,
        feedbackScore: 4.6,
        certificationProvided: 'Yes',
        status: 'Completed',
        remarks: 'Cloud certification',
      },
    ],
  },
  {
    id: 'placement-statistics',
    label: 'Placement Statistics',
    icon: 'BarChart3',
    description: 'Year-wise and department-wise placement statistics and analytics',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'totalEligible', label: 'Total Eligible', type: 'number', required: true },
      { key: 'totalPlaced', label: 'Total Placed', type: 'number', required: true },
      { key: 'placementPercentage', label: 'Placement %', type: 'percentage' },
      { key: 'highestPackage', label: 'Highest Package (LPA)', type: 'currency' },
      { key: 'averagePackage', label: 'Average Package (LPA)', type: 'currency' },
      { key: 'medianPackage', label: 'Median Package (LPA)', type: 'currency' },
      { key: 'lowestPackage', label: 'Lowest Package (LPA)', type: 'currency' },
      { key: 'totalOffers', label: 'Total Offers', type: 'number' },
      { key: 'companiesVisited', label: 'Companies Visited', type: 'number' },
      { key: 'higherEducation', label: 'Higher Education', type: 'number' },
      { key: 'entrepreneurs', label: 'Entrepreneurs', type: 'number' },
    ],
    sampleData: [
      {
        academicYear: '2023-24',
        department: 'Computer Science',
        totalEligible: 120,
        totalPlaced: 108,
        placementPercentage: 90,
        highestPackage: 32.0,
        averagePackage: 8.5,
        medianPackage: 7.2,
        lowestPackage: 4.5,
        totalOffers: 135,
        companiesVisited: 45,
        higherEducation: 8,
        entrepreneurs: 4,
      },
      {
        academicYear: '2023-24',
        department: 'Electronics',
        totalEligible: 60,
        totalPlaced: 48,
        placementPercentage: 80,
        highestPackage: 18.0,
        averagePackage: 6.8,
        medianPackage: 6.0,
        lowestPackage: 4.0,
        totalOffers: 55,
        companiesVisited: 30,
        higherEducation: 6,
        entrepreneurs: 2,
      },
      {
        academicYear: '2023-24',
        department: 'Mechanical',
        totalEligible: 90,
        totalPlaced: 63,
        placementPercentage: 70,
        highestPackage: 12.0,
        averagePackage: 5.5,
        medianPackage: 5.0,
        lowestPackage: 3.5,
        totalOffers: 70,
        companiesVisited: 25,
        higherEducation: 12,
        entrepreneurs: 3,
      },
      {
        academicYear: '2023-24',
        department: 'Civil',
        totalEligible: 60,
        totalPlaced: 36,
        placementPercentage: 60,
        highestPackage: 8.0,
        averagePackage: 4.8,
        medianPackage: 4.5,
        lowestPackage: 3.2,
        totalOffers: 40,
        companiesVisited: 18,
        higherEducation: 10,
        entrepreneurs: 2,
      },
    ],
  },
];

export const tpoDocumentCategories = [
  { id: 'placement-reports', label: 'Annual Placement Reports', count: 6 },
  { id: 'mou-agreements', label: 'MoU & Recruiter Agreements', count: 18 },
  { id: 'offer-letters', label: 'Offer Letters & Appointment Orders', count: 45 },
  { id: 'internship-certificates', label: 'Internship Certificates', count: 80 },
  { id: 'training-certificates', label: 'Training & Certification Records', count: 35 },
  { id: 'higher-education-proofs', label: 'Higher Education Admission Proofs', count: 25 },
  { id: 'startup-documents', label: 'Startup Registration & Funding Docs', count: 12 },
  { id: 'feedback-forms', label: 'Employer & Student Feedback', count: 30 },
  { id: 'event-reports', label: 'Placement Drive & Event Reports', count: 15 },
  { id: 'alumni-records', label: 'Alumni Placement Records', count: 20 },
  { id: 'skill-assessments', label: 'Skill Assessment Reports', count: 22 },
  { id: 'compliance-docs', label: 'NAAC/NBA Compliance Documents', count: 10 },
];
