export type InstitutionStatus = 'ACTIVE' | 'INACTIVE' | 'PENDING' | 'SUSPENDED';
export type InstitutionCategory = 'Engineering' | 'Medical' | 'Arts & Science' | 'Management' | 'Law' | 'Education' | 'Pharmacy';

/**
 * Institution as returned by the GET /api/admin/institutions API.
 * All fields match the backend response shape.
 */
export interface Institution {
  id: number;
  name: string;
  code: string;
  category: string;
  typeOfInstitution: string;
  ownershipStatus: string;
  website: string;
  email: string;
  phone: string;
  logo: string;
  aicteCode: string;
  aisheCode: string;
  ugcCode: string;
  yearOfEstablishment: string;
  affiliatedUniversity: string;
  affiliatedUniversityAddress: string;
  addressLine1: string | null;
  addressLine2: string | null;
  landmark: string | null;
  city: string;
  district: string;
  state: string;
  pincode: string | null;
  ruralUrbanStatus: string | null;
  geoLatitude: string | null;
  geoLongitude: string | null;
  mission: string | null;
  vision: string | null;
  coreValues: string | null;
  qualityPolicy: string | null;
  motto: string | null;
  naacAccreditationStatus: string | null;
  naacGrade: string | null;
  naacCgpa: string | null;
  naacCycle: string | null;
  naacValidFrom: string | null;
  naacValidUpto: string | null;
  naacCertificateNumber: string | null;
  nbaAccreditationStatus: string | null;
  nbaProgramsAccredited: string | null;
  nbaValidFrom: string | null;
  nbaValidUpto: string | null;
  nbaTier: string | null;
  nirfParticipationStatus: string | null;
  nirfRank: string | null;
  nirfYear: string | null;
  nirfCategory: string | null;
  nirfScore: string | null;
  autonomousStatus: string | null;
  autonomousGrantedBy: string | null;
  autonomousGrantedDate: string | null;
  autonomousValidUpto: string | null;
  autonomousOrderNumber: string | null;
  ugcRecognitionStatus: string | null;
  ugcSection2f: string | null;
  ugcSection12b: string | null;
  ugcRecognitionDate: string | null;
  ugcLetterNumber: string | null;
  aicteApprovalStatus: string | null;
  aicteApplicationId: string | null;
  aicteApprovalYear: string | null;
  aicteEoa: string | null;
  aictePermanentId: string | null;
  status: InstitutionStatus;
  usersCount: number;
  repositoryCompletion: number;
  documentsUploaded: number;
  createdAt: string;
  updatedAt: string;
}

export interface InstitutionFilters {
  search: string;
  status: InstitutionStatus | 'all';
  category: InstitutionCategory | 'all';
  state: string | 'all';
  repositoryCompletion: 'all' | 'below-50' | '50-75' | 'above-75';
}

export interface InstitutionSortConfig {
  key: keyof Institution;
  direction: 'asc' | 'desc';
}

export interface PaginationConfig {
  page: number;
  pageSize: number;
  total: number;
  totalPages: number;
}

/**
 * Raw API response shape from GET /api/admin/institutions.
 * The apiService unwraps ApiResponse<T>, so this is the inner data.
 */
export interface InstitutionListApiResponse {
  data: Institution[];
  pagination: PaginationConfig;
}

export interface InstitutionQueryParams {
  page: number;
  pageSize: number;
  search?: string;
  status?: string;
  category?: string;
  state?: string;
  repositoryCompletion?: string;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
}

// ── Create Institution API Types ──

/**
 * POST /api/admin/institutions request body (new nested structure).
 * Matches the form data shape 1:1 — no transformation needed.
 */
export interface CreateInstitutionRequest {
  basicInfo: {
    name: string;
    code: string;
    category: string;
    email: string;
    phone: string;
    website: string;
    logo: string;
  };
  address: {
    addressLine1: string;
    addressLine2: string;
    state: string;
    district: string;
    pincode: string;
  };
  academicConfig: {
    programs: string[];
    departments: string[];
  };
  academicYears: {
    academicYears: string[];
  };
  admin: {
    name: string;
    email: string;
    mobile: string;
    autoGeneratePassword: boolean;
  };
  iqacCoordinator: {
    name: string;
    email: string;
    mobile: string;
    autoGeneratePassword: boolean;
  };
  principal: {
    name: string;
    email: string;
    mobile: string;
    autoGeneratePassword: boolean;
  };
}

/** User created as part of institution creation */
export interface CreatedUser {
  id: number;
  name: string;
  email: string;
  role: string;
  mobile: string;
  temporaryPassword: string;
  autoGenerated: boolean;
  requiresPasswordChange: boolean;
}

/** Summary institution object returned inside the GET-by-ID response */
export interface InstitutionSummary {
  id: number;
  name: string;
  code: string;
  category: string;
  email: string;
  phone: string;
  website: string;
  state: string;
  city: string;
  status: string;
  logoUrl: string | null;
  establishedYear: string | null;
  addressLine1: string | null;
  addressLine2: string | null;
  pincode: string | null;
  createdAt: string;
  updatedAt: string;
}

/** A single academic year entry returned inside GET-by-ID */
export interface AcademicYear {
  id: number;
  year: string;
  status: string;
}

/**
 * POST /api/admin/institutions response (apiService unwraps ApiResponse,
 * so this is the shape of the `data` field).
 *
 * Also the shape returned by GET /api/admin/institutions/{id}.
 */
export interface CreateInstitutionResponse {
  institution: InstitutionSummary;
  usersCreated: number;
  adminUser: CreatedUser;
  iqacUser: CreatedUser;
  principalUser: CreatedUser;
  academicEntities: {
    programsCreated: number;
    departmentsCreated: number;
    academicYearsCreated: number;
    academicYears: AcademicYear[];
  };
}

/**
 * Alias — the GET /api/admin/institutions/{id} endpoint returns
 * the same shape as the create response.
 */
export type InstitutionDetailResponse = CreateInstitutionResponse;