import {
  InstitutionProfile,
  Program,
  Department,
  Specialization,
  AcademicYear,
  AcademicRegulation,
  ProgramOffering,
  ProgramIntake,
  InstitutionUser,
  RoleInfo,
  RepositoryMetric,
  DepartmentReadiness,
  ActivityLog,
} from './types';

export const institutionProfile: InstitutionProfile = {
  name: 'Sri Venkateswara College of Engineering',
  code: 'SVCE2024',
  category: 'Self-Financing',
  website: 'https://www.svce.ac.in',
  email: 'info@svce.ac.in',
  phone: '+91-44-27152000',
  logo: '',
  aicteCode: '1-4726181',
  aisheCode: 'C-42587',
  ugcCode: 'TN-2024-0156',
  yearOfEstablishment: '1985',
  typeOfInstitution: 'Autonomous',
  ownershipStatus: 'Trust',
  affiliatedUniversity: 'Anna University',
  affiliatedUniversityAddress: 'Guindy, Chennai - 600025, Tamil Nadu',
  missionVision: {
    mission: 'To provide quality technical education and foster innovation through excellence in teaching, research, and industry collaboration, thereby producing competent engineers and technologists who contribute to the advancement of society.',
    vision: 'To be a globally recognized institution of excellence in engineering education and research, nurturing ethical and socially responsible professionals who lead technological innovation and sustainable development.',
    coreValues: [
      'Excellence in Education',
      'Innovation and Creativity',
      'Integrity and Ethics',
      'Social Responsibility',
      'Inclusivity and Diversity',
      'Continuous Improvement',
      'Industry Collaboration',
      'Sustainability',
    ],
    qualityPolicy: 'Sri Venkateswara College of Engineering is committed to providing quality education through competent faculty, state-of-the-art infrastructure, and industry-relevant curriculum. We strive for continuous improvement in all academic and administrative processes to achieve excellence in technical education and research.',
    motto: 'Knowledge is Power - Vidya Shakti',
  },
  address: {
    line1: 'Post Bag No. 1, Pennalur',
    line2: 'Sriperumbudur Tk.',
    landmark: 'Near Sriperumbudur Bus Stand',
    city: 'Sriperumbudur',
    state: 'Tamil Nadu',
    district: 'Kanchipuram',
    pincode: '602117',
    ruralUrbanStatus: 'Urban',
    geoLatitude: '12.9634',
    geoLongitude: '79.9785',
  },
  contact: {
    principalName: 'Dr. S. Ganesh Vaidyanathan',
    principalEmail: 'principal@svce.ac.in',
    principalMobile: '+91-9876543210',
    iqacName: 'Dr. R. Kumar',
    iqacEmail: 'iqac@svce.ac.in',
    iqacMobile: '+91-9876543211',
  },
  naac: {
    accreditationStatus: 'Accredited',
    grade: 'A++',
    cgpa: '3.62',
    cycle: '3rd Cycle',
    validFrom: '2022-09-15',
    validUpto: '2027-09-14',
    certificateNumber: 'NAAC/A++/2022/TN/156',
  },
  nba: {
    accreditationStatus: 'Accredited',
    programsAccredited: 'CSE, ECE, EEE, MECH, IT',
    validFrom: '2023-07-01',
    validUpto: '2026-06-30',
    tier: 'Tier-I',
  },
  nirf: {
    participationStatus: 'Participating',
    rank: '45',
    year: '2025',
    category: 'Engineering',
    score: '58.72',
  },
  autonomous: {
    status: 'Autonomous',
    grantedBy: 'UGC',
    grantedDate: '2014-06-15',
    validUpto: '2029-06-14',
    orderNumber: 'UGC/AUTO/2014/TN/089',
  },
  ugcRecognition: {
    recognitionStatus: 'Recognized',
    section2f: 'Yes',
    section12b: 'Yes',
    recognitionDate: '1986-03-20',
    letterNumber: 'UGC/REC/1986/TN/042',
  },
  aicteApprovals: {
    approvalStatus: 'Approved',
    applicationId: 'AICTE-2025-TN-4726181',
    approvalYear: '2025-26',
    eoa: 'EOA/2025-26/TN/SVCE',
    permanentId: '1-4726181',
  },
};

export const masterPrograms: Program[] = [
  { id: '1', programCode: 'BTECH', name: 'B.Tech', level: 'UG', duration: 4, status: 'active', enabled: true, isCustom: false },
  { id: '2', programCode: 'MTECH', name: 'M.Tech', level: 'PG', duration: 2, status: 'active', enabled: true, isCustom: false },
  { id: '3', programCode: 'MBA', name: 'MBA', level: 'PG', duration: 2, status: 'active', enabled: true, isCustom: false },
  { id: '4', programCode: 'MCA', name: 'MCA', level: 'PG', duration: 2, status: 'inactive', enabled: false, isCustom: false },
  { id: '5', programCode: 'PHD', name: 'PhD', level: 'Doctoral', duration: 4, status: 'active', enabled: true, isCustom: false },
];

export const departments: Department[] = [
  { id: '1', name: 'Computer Science & Engineering', code: 'CSE', program: 'B.Tech', programId: '1', coordinator: 'Dr. Rajesh Kumar', repositoryCompletion: 91, establishedYear: 1985, status: 'active', enabled: true },
  { id: '2', name: 'Information Technology', code: 'IT', program: 'B.Tech', programId: '1', coordinator: 'Dr. Priya Sharma', repositoryCompletion: 85, establishedYear: 1998, status: 'active', enabled: true },
  { id: '3', name: 'Artificial Intelligence & ML', code: 'AI&ML', program: 'B.Tech', programId: '1', coordinator: 'Dr. Suresh Babu', repositoryCompletion: 78, establishedYear: 2020, status: 'active', enabled: true },
  { id: '4', name: 'AI & Data Science', code: 'AI&DS', program: 'B.Tech', programId: '1', coordinator: 'Dr. Meena Kumari', repositoryCompletion: 72, establishedYear: 2021, status: 'active', enabled: true },
  { id: '5', name: 'Electronics & Communication', code: 'ECE', program: 'B.Tech', programId: '1', coordinator: 'Dr. Venkat Raman', repositoryCompletion: 88, establishedYear: 1985, status: 'active', enabled: true },
  { id: '6', name: 'Electrical & Electronics', code: 'EEE', program: 'B.Tech', programId: '1', coordinator: 'Dr. Lakshmi Devi', repositoryCompletion: 82, establishedYear: 1985, status: 'active', enabled: true },
  { id: '7', name: 'Mechanical Engineering', code: 'MECH', program: 'B.Tech', programId: '1', coordinator: 'Dr. Arun Prakash', repositoryCompletion: 79, establishedYear: 1985, status: 'active', enabled: true },
  { id: '8', name: 'Civil Engineering', code: 'CIVIL', program: 'B.Tech', programId: '1', coordinator: 'Dr. Karthik Raja', repositoryCompletion: 75, establishedYear: 1985, status: 'active', enabled: true },
  { id: '9', name: 'Chemical Engineering', code: 'CHEMICAL', program: 'B.Tech', programId: '1', coordinator: '', repositoryCompletion: 0, establishedYear: 1990, status: 'inactive', enabled: false },
  { id: '10', name: 'Biotechnology', code: 'BIOTECHNOLOGY', program: 'B.Tech', programId: '1', coordinator: '', repositoryCompletion: 0, establishedYear: 2005, status: 'inactive', enabled: false },
  { id: '11', name: 'Automobile Engineering', code: 'AUTOMOBILE', program: 'B.Tech', programId: '1', coordinator: '', repositoryCompletion: 0, establishedYear: 2008, status: 'inactive', enabled: false },
  { id: '12', name: 'Aeronautical Engineering', code: 'AERONAUTICAL', program: 'B.Tech', programId: '1', coordinator: '', repositoryCompletion: 0, establishedYear: 2010, status: 'inactive', enabled: false },
];

export const specializations: Specialization[] = [
  { id: '1', name: 'Artificial Intelligence', departmentId: '1', departmentName: 'CSE', status: 'active', enabled: true },
  { id: '2', name: 'Data Science', departmentId: '1', departmentName: 'CSE', status: 'active', enabled: true },
  { id: '3', name: 'Cyber Security', departmentId: '1', departmentName: 'CSE', status: 'active', enabled: true },
  { id: '4', name: 'IoT', departmentId: '1', departmentName: 'CSE', status: 'active', enabled: true },
  { id: '5', name: 'Cloud Computing', departmentId: '1', departmentName: 'CSE', status: 'inactive', enabled: false },
  { id: '6', name: 'VLSI', departmentId: '5', departmentName: 'ECE', status: 'active', enabled: true },
  { id: '7', name: 'Embedded Systems', departmentId: '5', departmentName: 'ECE', status: 'active', enabled: true },
  { id: '8', name: 'Communication Systems', departmentId: '5', departmentName: 'ECE', status: 'active', enabled: true },
  { id: '9', name: 'Robotics', departmentId: '7', departmentName: 'MECH', status: 'active', enabled: true },
  { id: '10', name: 'Thermal Engineering', departmentId: '7', departmentName: 'MECH', status: 'active', enabled: true },
];

export const academicYears: AcademicYear[] = [
  { id: '1', year: '2025-26', startDate: '2025-06-01', endDate: '2026-05-31', institutionType: 'Autonomous', status: 'active' },
  { id: '2', year: '2024-25', startDate: '2024-06-01', endDate: '2025-05-31', institutionType: 'Autonomous', status: 'inactive' },
  { id: '3', year: '2023-24', startDate: '2023-06-01', endDate: '2024-05-31', institutionType: 'Autonomous', status: 'inactive' },
];

export const academicRegulations: AcademicRegulation[] = [
  {
    id: '1',
    regulationCode: 'R22',
    regulationName: 'Regulation 2022',
    program: 'B.Tech',
    programId: '1',
    academicYearIntroduced: '2022-23',
    effectiveFromBatch: '2022',
    effectiveToBatch: '2025',
    duration: 4,
    status: 'active',
    creditStructure: {
      totalCredits: 160,
      coreCredits: 90,
      professionalElectiveCredits: 24,
      openElectiveCredits: 12,
      laboratoryCredits: 20,
      projectCredits: 10,
      internshipCredits: 4,
    },
    evaluationScheme: {
      internalMarks: 40,
      externalMarks: 60,
      passingMarks: 50,
      gradingSystem: 'CGPA Based',
      cgpaScale: 10,
      maxPercentage: 100,
    },
    internshipRequirements: {
      internshipMandatory: true,
      internshipDuration: '8 weeks',
      industryTrainingMandatory: true,
    },
    projectRequirements: {
      miniProjectMandatory: true,
      majorProjectMandatory: true,
      capstoneProjectMandatory: false,
    },
    approvals: {
      approvedBy: 'Academic Council',
      approvalDate: '2022-03-15',
      bosApproval: 'Approved - BoS/2022/03',
      academicCouncilApproval: 'Approved - AC/2022/04',
    },
    documents: ['Academic Regulation Book', 'Academic Council Approval', 'BoS Minutes', 'Credit Structure Document'],
  },
  {
    id: '2',
    regulationCode: 'R20',
    regulationName: 'Regulation 2020',
    program: 'B.Tech',
    programId: '1',
    academicYearIntroduced: '2020-21',
    effectiveFromBatch: '2020',
    effectiveToBatch: '2023',
    duration: 4,
    status: 'active',
    creditStructure: {
      totalCredits: 156,
      coreCredits: 88,
      professionalElectiveCredits: 22,
      openElectiveCredits: 12,
      laboratoryCredits: 20,
      projectCredits: 10,
      internshipCredits: 4,
    },
    evaluationScheme: {
      internalMarks: 40,
      externalMarks: 60,
      passingMarks: 50,
      gradingSystem: 'CGPA Based',
      cgpaScale: 10,
      maxPercentage: 100,
    },
    internshipRequirements: {
      internshipMandatory: true,
      internshipDuration: '6 weeks',
      industryTrainingMandatory: false,
    },
    projectRequirements: {
      miniProjectMandatory: true,
      majorProjectMandatory: true,
      capstoneProjectMandatory: false,
    },
    approvals: {
      approvedBy: 'Academic Council',
      approvalDate: '2020-02-20',
      bosApproval: 'Approved - BoS/2020/02',
      academicCouncilApproval: 'Approved - AC/2020/03',
    },
    documents: ['Academic Regulation Book', 'Academic Council Approval', 'BoS Minutes'],
  },
  {
    id: '3',
    regulationCode: 'R18',
    regulationName: 'Regulation 2018',
    program: 'B.Tech',
    programId: '1',
    academicYearIntroduced: '2018-19',
    effectiveFromBatch: '2018',
    effectiveToBatch: '2021',
    duration: 4,
    status: 'inactive',
    creditStructure: {
      totalCredits: 152,
      coreCredits: 86,
      professionalElectiveCredits: 20,
      openElectiveCredits: 12,
      laboratoryCredits: 20,
      projectCredits: 10,
      internshipCredits: 4,
    },
    evaluationScheme: {
      internalMarks: 30,
      externalMarks: 70,
      passingMarks: 50,
      gradingSystem: 'CGPA Based',
      cgpaScale: 10,
      maxPercentage: 100,
    },
    internshipRequirements: {
      internshipMandatory: false,
      internshipDuration: '',
      industryTrainingMandatory: false,
    },
    projectRequirements: {
      miniProjectMandatory: false,
      majorProjectMandatory: true,
      capstoneProjectMandatory: false,
    },
    approvals: {
      approvedBy: 'Academic Council',
      approvalDate: '2018-03-10',
      bosApproval: 'Approved - BoS/2018/02',
      academicCouncilApproval: 'Approved - AC/2018/03',
    },
    documents: ['Academic Regulation Book', 'Academic Council Approval'],
  },
  {
    id: '4',
    regulationCode: 'R24',
    regulationName: 'Regulation 2024',
    program: 'B.Tech',
    programId: '1',
    academicYearIntroduced: '2024-25',
    effectiveFromBatch: '2024',
    effectiveToBatch: '2027',
    duration: 4,
    status: 'active',
    creditStructure: {
      totalCredits: 164,
      coreCredits: 92,
      professionalElectiveCredits: 26,
      openElectiveCredits: 14,
      laboratoryCredits: 18,
      projectCredits: 10,
      internshipCredits: 4,
    },
    evaluationScheme: {
      internalMarks: 40,
      externalMarks: 60,
      passingMarks: 50,
      gradingSystem: 'Percentage Based',
      cgpaScale: 10,
      maxPercentage: 100,
    },
    internshipRequirements: {
      internshipMandatory: true,
      internshipDuration: '12 weeks',
      industryTrainingMandatory: true,
    },
    projectRequirements: {
      miniProjectMandatory: true,
      majorProjectMandatory: true,
      capstoneProjectMandatory: true,
    },
    approvals: {
      approvedBy: 'Academic Council',
      approvalDate: '2024-02-28',
      bosApproval: 'Approved - BoS/2024/02',
      academicCouncilApproval: 'Approved - AC/2024/03',
    },
    documents: ['Academic Regulation Book', 'Academic Council Approval', 'BoS Minutes', 'Credit Structure Document'],
  },
];

export const programOfferings: ProgramOffering[] = [
  { id: '1', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'CSE', departmentId: '1', specialization: 'Artificial Intelligence', specializationId: '1', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech CSE AI 2025-26 R22' },
  { id: '2', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'CSE', departmentId: '1', specialization: 'Data Science', specializationId: '2', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech CSE DS 2025-26 R22' },
  { id: '3', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'CSE', departmentId: '1', specialization: 'Cyber Security', specializationId: '3', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech CSE CS 2025-26 R22' },
  { id: '4', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'ECE', departmentId: '5', specialization: 'VLSI', specializationId: '6', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech ECE VLSI 2025-26 R22' },
  { id: '5', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'ECE', departmentId: '5', specialization: 'Embedded Systems', specializationId: '7', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech ECE ES 2025-26 R22' },
  { id: '6', academicYear: '2025-26', academicYearId: '1', program: 'B.Tech', programId: '1', department: 'MECH', departmentId: '7', specialization: 'Robotics', specializationId: '9', regulation: 'R22', regulationId: '1', duration: 4, status: 'active', generatedName: 'B.Tech MECH Robotics 2025-26 R22' },
  { id: '7', academicYear: '2024-25', academicYearId: '2', program: 'B.Tech', programId: '1', department: 'CSE', departmentId: '1', specialization: 'Artificial Intelligence', specializationId: '1', regulation: 'R20', regulationId: '2', duration: 4, status: 'active', generatedName: 'B.Tech CSE AI 2024-25 R20' },
  { id: '8', academicYear: '2025-26', academicYearId: '1', program: 'M.Tech', programId: '2', department: 'CSE', departmentId: '1', specialization: 'Artificial Intelligence', specializationId: '1', regulation: 'R22', regulationId: '1', duration: 2, status: 'active', generatedName: 'M.Tech CSE AI 2025-26 R22' },
];

export const programIntakes: ProgramIntake[] = [
  { id: '1', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech CSE AI 2025-26 R22', programOfferingId: '1', sanctionedIntake: 120, admittedIntake: 118, lateralEntryIntake: 12, vacantSeats: 0, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter', 'University Approval'] },
  { id: '2', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech CSE DS 2025-26 R22', programOfferingId: '2', sanctionedIntake: 60, admittedIntake: 58, lateralEntryIntake: 6, vacantSeats: 0, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter', 'University Approval'] },
  { id: '3', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech CSE CS 2025-26 R22', programOfferingId: '3', sanctionedIntake: 60, admittedIntake: 55, lateralEntryIntake: 6, vacantSeats: 0, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter'] },
  { id: '4', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech ECE VLSI 2025-26 R22', programOfferingId: '4', sanctionedIntake: 120, admittedIntake: 110, lateralEntryIntake: 12, vacantSeats: 0, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter', 'University Approval', 'Seat Matrix'] },
  { id: '5', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech ECE ES 2025-26 R22', programOfferingId: '5', sanctionedIntake: 60, admittedIntake: 52, lateralEntryIntake: 6, vacantSeats: 2, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter'] },
  { id: '6', academicYear: '2025-26', academicYearId: '1', programOffering: 'B.Tech MECH Robotics 2025-26 R22', programOfferingId: '6', sanctionedIntake: 120, admittedIntake: 95, lateralEntryIntake: 12, vacantSeats: 13, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter', 'University Approval'] },
  { id: '7', academicYear: '2025-26', academicYearId: '1', programOffering: 'M.Tech CSE AI 2025-26 R22', programOfferingId: '8', sanctionedIntake: 18, admittedIntake: 15, lateralEntryIntake: 0, vacantSeats: 3, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter'] },
  { id: '8', academicYear: '2024-25', academicYearId: '2', programOffering: 'B.Tech CSE AI 2024-25 R20', programOfferingId: '7', sanctionedIntake: 120, admittedIntake: 120, lateralEntryIntake: 12, vacantSeats: 0, approvalAuthority: 'AICTE', status: 'active', documents: ['AICTE Approval Letter', 'University Approval', 'Seat Matrix'] },
];

export const institutionUsers: InstitutionUser[] = [
  { id: '1', name: 'Dr. S. Ganesh Vaidyanathan', email: 'principal@svce.ac.in', mobile: '+91-9876543210', role: 'Institution Admin', department: '-', status: 'active', lastLogin: '2026-06-16 09:30' },
  { id: '2', name: 'Dr. R. Kumar', email: 'iqac@svce.ac.in', mobile: '+91-9876543211', role: 'IQAC Coordinator', department: '-', status: 'active', lastLogin: '2026-06-16 08:45' },
  { id: '3', name: 'Dr. Rajesh Kumar', email: 'rajesh.k@svce.ac.in', mobile: '+91-9876543212', role: 'Department Coordinator', department: 'CSE', status: 'active', lastLogin: '2026-06-15 16:20' },
  { id: '4', name: 'Dr. Priya Sharma', email: 'priya.s@svce.ac.in', mobile: '+91-9876543213', role: 'Department Coordinator', department: 'IT', status: 'active', lastLogin: '2026-06-15 14:10' },
  { id: '5', name: 'Dr. Suresh Babu', email: 'suresh.b@svce.ac.in', mobile: '+91-9876543214', role: 'Department Coordinator', department: 'AI&ML', status: 'active', lastLogin: '2026-06-14 11:30' },
  { id: '6', name: 'Dr. Venkat Raman', email: 'venkat.r@svce.ac.in', mobile: '+91-9876543215', role: 'Department Coordinator', department: 'ECE', status: 'active', lastLogin: '2026-06-15 09:45' },
  { id: '7', name: 'Dr. Lakshmi Devi', email: 'lakshmi.d@svce.ac.in', mobile: '+91-9876543216', role: 'Department Coordinator', department: 'EEE', status: 'inactive', lastLogin: '2026-06-10 15:00' },
  { id: '8', name: 'Dr. Arun Prakash', email: 'arun.p@svce.ac.in', mobile: '+91-9876543217', role: 'Department Coordinator', department: 'MECH', status: 'active', lastLogin: '2026-06-15 10:20' },
  { id: '9', name: 'Dr. Karthik Raja', email: 'karthik.r@svce.ac.in', mobile: '+91-9876543218', role: 'Department Coordinator', department: 'CIVIL', status: 'blocked', lastLogin: '2026-06-01 08:00' },
  { id: '10', name: 'Dr. Meena Kumari', email: 'meena.k@svce.ac.in', mobile: '+91-9876543219', role: 'Research Coordinator', department: '-', status: 'pending', lastLogin: '-' },
  { id: '11', name: 'Mr. Srinivas Rao', email: 'srinivas.r@svce.ac.in', mobile: '+91-9876543220', role: 'Placement Officer', department: '-', status: 'active', lastLogin: '2026-06-14 12:00' },
  { id: '12', name: 'Dr. Anitha Kumari', email: 'anitha.k@svce.ac.in', mobile: '+91-9876543221', role: 'Examination Officer', department: '-', status: 'active', lastLogin: '2026-06-13 16:30' },
];

export const roles: RoleInfo[] = [
  { name: 'Institution Admin', usersAssigned: 1, permissions: ['Institution Profile', 'Academic Structure', 'User Management', 'Role Management', 'Repository Monitoring', 'Readiness Dashboard', 'Activity Logs', 'Settings'] },
  { name: 'IQAC Coordinator', usersAssigned: 1, permissions: ['Academic Repository', 'Faculty Repository', 'Student Repository', 'Research Repository', 'Evidence Verification', 'Repository Approval'] },
  { name: 'Department Coordinator', usersAssigned: 8, permissions: ['Academic Repository', 'Faculty Repository', 'Student Repository', 'Research Repository'] },
  { name: 'Research Coordinator', usersAssigned: 1, permissions: ['Research Repository', 'Publication Management', 'Patent Management'] },
  { name: 'Placement Officer', usersAssigned: 1, permissions: ['Student Repository', 'Placement Data', 'Company Management'] },
  { name: 'Examination Officer', usersAssigned: 1, permissions: ['Student Repository', 'Examination Data', 'Result Management'] },
  { name: 'Compliance Officer', usersAssigned: 0, permissions: ['Compliance Repository', 'Audit Management', 'Report Generation'] },
];

export const repositoryMetrics: RepositoryMetric[] = [
  { name: 'Academic Repository', dataCompleteness: 92, evidenceCompleteness: 85, verificationScore: 88, readinessScore: 88 },
  { name: 'Faculty Repository', dataCompleteness: 88, evidenceCompleteness: 80, verificationScore: 82, readinessScore: 83 },
  { name: 'Student Repository', dataCompleteness: 95, evidenceCompleteness: 90, verificationScore: 91, readinessScore: 92 },
  { name: 'Research Repository', dataCompleteness: 78, evidenceCompleteness: 72, verificationScore: 75, readinessScore: 75 },
];

export const departmentReadiness: DepartmentReadiness[] = [
  { department: 'CSE', academic: 100, faculty: 95, student: 98, research: 85, evidence: 80, overall: 91 },
  { department: 'IT', academic: 92, faculty: 88, student: 90, research: 78, evidence: 75, overall: 85 },
  { department: 'AI&ML', academic: 85, faculty: 80, student: 82, research: 70, evidence: 68, overall: 78 },
  { department: 'AI&DS', academic: 80, faculty: 75, student: 78, research: 65, evidence: 60, overall: 72 },
  { department: 'ECE', academic: 95, faculty: 90, student: 92, research: 82, evidence: 78, overall: 88 },
  { department: 'EEE', academic: 90, faculty: 85, student: 88, research: 75, evidence: 72, overall: 82 },
  { department: 'MECH', academic: 88, faculty: 82, student: 85, research: 70, evidence: 65, overall: 79 },
  { department: 'CIVIL', academic: 82, faculty: 78, student: 80, research: 65, evidence: 62, overall: 75 },
];

export const activityLogs: ActivityLog[] = [
  { id: '1', user: 'Dr. Rajesh Kumar', role: 'Department Coordinator', action: 'Uploaded faculty_profiles.csv', module: 'Faculty Repository', date: '2026-06-16', time: '09:30' },
  { id: '2', user: 'Dr. R. Kumar', role: 'IQAC Coordinator', action: 'Verified curriculum evidence', module: 'Academic Repository', date: '2026-06-16', time: '08:45' },
  { id: '3', user: 'Dr. Priya Sharma', role: 'Department Coordinator', action: 'Uploaded student_results.csv', module: 'Student Repository', date: '2026-06-15', time: '16:20' },
  { id: '4', user: 'Dr. Venkat Raman', role: 'Department Coordinator', action: 'Uploaded research_publications.csv', module: 'Research Repository', date: '2026-06-15', time: '14:10' },
  { id: '5', user: 'Dr. Suresh Babu', role: 'Department Coordinator', action: 'Updated academic calendar', module: 'Academic Repository', date: '2026-06-15', time: '11:30' },
  { id: '6', user: 'Dr. R. Kumar', role: 'IQAC Coordinator', action: 'Approved CSE faculty data', module: 'Faculty Repository', date: '2026-06-14', time: '15:00' },
  { id: '7', user: 'Dr. Arun Prakash', role: 'Department Coordinator', action: 'Uploaded course_outcomes.csv', module: 'Academic Repository', date: '2026-06-14', time: '12:00' },
  { id: '8', user: 'Dr. Lakshmi Devi', role: 'Department Coordinator', action: 'Uploaded value_added_courses.csv', module: 'Academic Repository', date: '2026-06-13', time: '16:30' },
  { id: '9', user: 'Mr. Srinivas Rao', role: 'Placement Officer', action: 'Updated placement statistics', module: 'Student Repository', date: '2026-06-13', time: '10:45' },
  { id: '10', user: 'Dr. Anitha Kumari', role: 'Examination Officer', action: 'Uploaded exam results batch 2024', module: 'Student Repository', date: '2026-06-12', time: '14:20' },
];

export const dashboardKPIs = {
  totalDepartments: 8,
  totalPrograms: 4,
  totalUsers: 12,
  activeUsers: 9,
  blockedUsers: 1,
  repositoryCompletion: 84,
  pendingReviews: 12,
  pendingApprovals: 5,
  missingEvidence: 23,
  repositoryHealthScore: 85,
};

export const recentActivities = [
  { text: 'CSE uploaded faculty data', time: '2 hours ago', icon: 'upload' },
  { text: 'ECE uploaded student data', time: '4 hours ago', icon: 'upload' },
  { text: 'IQAC approved curriculum', time: '6 hours ago', icon: 'check' },
  { text: 'Research coordinator verified publication', time: '8 hours ago', icon: 'verify' },
  { text: 'MECH uploaded course outcomes', time: '1 day ago', icon: 'upload' },
  { text: 'IT department updated academic calendar', time: '1 day ago', icon: 'calendar' },
];