import {
  RepositoryModuleConfig,
  RepositorySummary,
  RepositoryMetrics,
  KPICard,
  MasterData,
  DepartmentInfo,
  UploadHistoryRecord,
  EvidenceDocument,
  WorkflowStep,
  ValidationResult,
} from './types';

// Institution Master Data (from Institution Admin configuration)
export const masterData: MasterData = {
  programs: ['B.Tech', 'M.Tech', 'Ph.D'],
  departments: ['CSE', 'ECE', 'EEE', 'MECH', 'Civil'],
  specializations: ['AI', 'Data Science', 'Cyber Security', 'IoT', 'VLSI', 'Cloud Computing'],
  academicYears: ['2025-26', '2024-25', '2023-24', '2022-23', '2021-22'],
  regulations: ['R22', 'R20', 'R18'],
  programOfferings: [
    'B.Tech CSE AI R22',
    'B.Tech CSE Data Science R22',
    'B.Tech CSE Cyber Security R22',
    'M.Tech CSE AI R22',
    'M.Tech CSE Data Science R20',
  ],
  platforms: ['NPTEL', 'SWAYAM', 'Coursera', 'Udemy', 'edX', 'Others'],
};

// Current coordinator context
export const coordinatorContext = {
  department: 'CSE',
  role: 'DEPARTMENT_COORDINATOR',
  academicYear: '2025-26',
};

// Department Information
export const departmentInfo: DepartmentInfo = {
  department: 'Computer Science & Engineering (CSE)',
  programOfferings: [
    'B.Tech CSE AI R22',
    'B.Tech CSE Data Science R22',
    'B.Tech CSE Cyber Security R22',
    'M.Tech CSE AI R22',
    'M.Tech CSE Data Science R20',
  ],
  specializations: ['AI', 'Data Science', 'Cyber Security'],
  coordinatorName: 'Dr. Anita Sharma',
  academicYear: '2025-26',
};

// ============ ACADEMIC REPOSITORY ============
export const academicRepositoryConfig: RepositoryModuleConfig = {
  id: 'academic',
  label: 'Academic Repository',
  description: 'Maintain academic repository data for the assigned department',
  icon: 'GraduationCap',
  color: 'text-violet-600',
  gradient: 'from-violet-500 to-violet-600',
  tabs: [
    {
      id: 'curriculum',
      label: 'Curriculum',
      icon: 'BookOpen',
      fields: [
        { key: 'program', label: 'Program', type: 'select', required: true, csvColumn: 'Program', masterDataSource: 'programOfferings' },
        { key: 'academicRegulation', label: 'Academic Regulation', type: 'select', required: true, csvColumn: 'Academic Regulation', masterDataSource: 'regulations' },
        { key: 'totalCredits', label: 'Total Credits', type: 'number', required: true, csvColumn: 'Total Credits', validationRules: ['> 0'] },
        { key: 'openElectives', label: 'Open Electives Available', type: 'number', required: true, csvColumn: 'Open Electives Available' },
        { key: 'professionalElectives', label: 'Professional Electives Available', type: 'number', required: true, csvColumn: 'Professional Electives Available' },
        { key: 'valueAddedCourses', label: 'Value Added Courses Available', type: 'number', required: true, csvColumn: 'Value Added Courses Available' },
        { key: 'internshipIncluded', label: 'Internship Included', type: 'boolean', required: true, csvColumn: 'Internship Included' },
        { key: 'projectIncluded', label: 'Project Work Included', type: 'boolean', required: true, csvColumn: 'Project Work Included' },
        { key: 'industryCourses', label: 'Industry Courses Included', type: 'boolean', required: true, csvColumn: 'Industry Courses Included' },
        { key: 'revisionDate', label: 'Revision Date', type: 'date', required: true, csvColumn: 'Revision Date' },
      ],
      requiredEvidence: ['Curriculum Structure', 'Regulation Document', 'BoS Minutes', 'Curriculum Revision Approval'],
      validationRules: [
        'Program Offering must exist in master data',
        'Academic Regulation must exist in master data',
        'Total Credits must be > 0',
        'No duplicate Program + Regulation combination',
      ],
      templateFile: '/templates/curriculum_template.csv',
    },
    {
      id: 'courses',
      label: 'Courses',
      icon: 'FileText',
      fields: [
        { key: 'courseCode', label: 'Course Code', type: 'text', required: true, csvColumn: 'Course Code', validationRules: ['unique'] },
        { key: 'courseName', label: 'Course Name', type: 'text', required: true, csvColumn: 'Course Name' },
        { key: 'program', label: 'Program', type: 'select', required: true, csvColumn: 'Program', masterDataSource: 'programOfferings' },
        { key: 'semester', label: 'Semester', type: 'number', required: true, csvColumn: 'Semester', validationRules: ['1-8'] },
        { key: 'courseType', label: 'Course Type', type: 'select', required: true, csvColumn: 'Course Type', selectOptions: ['Theory', 'Lab', 'Theory + Lab', 'Project', 'Seminar', 'Internship'] },
        { key: 'credits', label: 'Credits', type: 'number', required: true, csvColumn: 'Credits', validationRules: ['> 0'] },
        { key: 'theoryHours', label: 'Theory Hours', type: 'number', required: true, csvColumn: 'Theory Hours' },
        { key: 'labHours', label: 'Lab Hours', type: 'number', required: true, csvColumn: 'Lab Hours' },
        { key: 'status', label: 'Status', type: 'select', required: true, csvColumn: 'Status', selectOptions: ['Active', 'Inactive', 'Proposed'] },
      ],
      requiredEvidence: ['Syllabus', 'Curriculum Document', 'Course Structure'],
      validationRules: [
        'Course Code must be unique',
        'Program must exist in master data',
        'Credits must be > 0',
        'Semester must be valid (1-8)',
      ],
      templateFile: '/templates/courses_template.csv',
    },
    {
      id: 'academic-calendar',
      label: 'Academic Calendar',
      icon: 'Calendar',
      fields: [
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'semester', label: 'Semester', type: 'select', required: true, csvColumn: 'Semester', selectOptions: ['I', 'II', 'Summer'] },
        { key: 'startDate', label: 'Start Date', type: 'date', required: true, csvColumn: 'Start Date' },
        { key: 'endDate', label: 'End Date', type: 'date', required: true, csvColumn: 'End Date' },
        { key: 'instructionalDays', label: 'Instructional Days', type: 'number', required: true, csvColumn: 'Instructional Days' },
        { key: 'midExamDates', label: 'Mid Exam Dates', type: 'text', required: true, csvColumn: 'Mid Exam Dates' },
        { key: 'endExamDates', label: 'End Exam Dates', type: 'text', required: true, csvColumn: 'End Exam Dates' },
      ],
      requiredEvidence: ['Academic Calendar PDF', 'Semester Schedule', 'Exam Schedule'],
      validationRules: [
        'Academic Year must exist in master data',
        'Start Date must be before End Date',
        'Semester must be valid',
      ],
      templateFile: '/templates/academic_calendar_template.csv',
    },
    {
      id: 'value-added-courses',
      label: 'Value Added Courses',
      icon: 'Award',
      fields: [
        { key: 'courseName', label: 'Course Name', type: 'text', required: true, csvColumn: 'Course Name' },
        { key: 'conductingUnit', label: 'Conducting Unit', type: 'text', required: true, csvColumn: 'Conducting Unit', autoPopulate: true },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'durationHours', label: 'Duration Hours', type: 'number', required: true, csvColumn: 'Duration Hours', validationRules: ['> 0'] },
        { key: 'studentsEnrolled', label: 'Students Enrolled', type: 'number', required: true, csvColumn: 'Students Enrolled', validationRules: ['>= 0'] },
        { key: 'certificationProvided', label: 'Certification Provided', type: 'boolean', required: true, csvColumn: 'Certification Provided' },
      ],
      requiredEvidence: ['Course Brochure', 'Attendance Records', 'Certificates', 'Completion Report'],
      validationRules: [
        'Academic Year must exist in master data',
        'Duration Hours must be > 0',
        'Students Enrolled must be >= 0',
      ],
      templateFile: '/templates/value_added_courses_template.csv',
    },
    {
      id: 'moocs',
      label: 'MOOCs / SWAYAM / NPTEL',
      icon: 'Globe',
      fields: [
        { key: 'platformName', label: 'Platform Name', type: 'select', required: true, csvColumn: 'Platform Name', masterDataSource: 'platforms' },
        { key: 'courseName', label: 'Course Name', type: 'text', required: true, csvColumn: 'Course Name' },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'studentsEnrolled', label: 'Students Enrolled', type: 'number', required: true, csvColumn: 'Students Enrolled' },
        { key: 'certificationsEarned', label: 'Certifications Earned', type: 'number', required: true, csvColumn: 'Certifications Earned' },
      ],
      requiredEvidence: ['Completion Reports', 'Certificates', 'Enrollment Reports'],
      validationRules: [
        'Academic Year must exist in master data',
        'Certifications Earned must be <= Students Enrolled',
      ],
      templateFile: '/templates/moocs_template.csv',
    },
    {
      id: 'supporting-documents',
      label: 'Supporting Documents',
      icon: 'FolderOpen',
      fields: [],
      requiredEvidence: [
        'Academic Regulations',
        'Curriculum Structure',
        'Syllabus',
        'Academic Calendar',
        'BoS Minutes',
        'Academic Council Minutes',
        'Value Added Course Brochures',
        'MOOC Reports',
        'Industry Course Evidence',
      ],
      validationRules: [],
      templateFile: '',
    },
  ],
};

// ============ FACULTY REPOSITORY ============
export const facultyRepositoryConfig: RepositoryModuleConfig = {
  id: 'faculty',
  label: 'Faculty Repository',
  description: 'Manage department faculty records including profiles, qualifications, employment, and FDPs',
  icon: 'Users',
  color: 'text-indigo-600',
  gradient: 'from-indigo-500 to-indigo-600',
  tabs: [
    {
      id: 'faculty-profiles',
      label: 'Faculty Profile',
      icon: 'UserCircle',
      fields: [
        { key: 'employeeId', label: 'Employee ID', type: 'text', required: true, csvColumn: 'Employee ID' },
        { key: 'facultyName', label: 'Faculty Name', type: 'text', required: true, csvColumn: 'Faculty Name' },
        { key: 'gender', label: 'Gender', type: 'select', required: true, csvColumn: 'Gender', selectOptions: ['Male', 'Female', 'Other'] },
        { key: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true, csvColumn: 'Date of Birth' },
        { key: 'panNumber', label: 'PAN Number', type: 'text', required: true, csvColumn: 'PAN Number' },
        { key: 'officialEmail', label: 'Official Email', type: 'text', required: true, csvColumn: 'Official Email' },
        { key: 'personalEmail', label: 'Personal Email', type: 'text', required: false, csvColumn: 'Personal Email' },
        { key: 'mobileNumber', label: 'Mobile Number', type: 'text', required: true, csvColumn: 'Mobile Number' },
        { key: 'academicUnit', label: 'Academic Unit', type: 'select', required: true, csvColumn: 'Academic Unit', masterDataSource: 'departments' },
        { key: 'designation', label: 'Designation', type: 'select', required: true, csvColumn: 'Designation', selectOptions: ['Professor', 'Associate Professor', 'Assistant Professor'] },
        { key: 'status', label: 'Status', type: 'select', required: true, csvColumn: 'Status', selectOptions: ['Active', 'Relieved'] },
      ],
      requiredEvidence: ['Appointment Order', 'PAN Card', 'Aadhaar', 'Institution Records', 'HR Records'],
      validationRules: [
        'Employee ID must be unique',
        'PAN Number must be valid format',
        'Official Email must be valid',
        'Academic Unit must exist in master data',
      ],
      templateFile: '/templates/faculty_profiles_template.csv',
    },
    {
      id: 'qualifications',
      label: 'Qualifications',
      icon: 'Award',
      fields: [
        { key: 'qualificationLevel', label: 'Qualification Level', type: 'select', required: true, csvColumn: 'Qualification Level', selectOptions: ['UG', 'PG', 'PhD', 'Post Doctoral'] },
        { key: 'degree', label: 'Degree', type: 'text', required: true, csvColumn: 'Degree' },
        { key: 'specialization', label: 'Specialization', type: 'text', required: true, csvColumn: 'Specialization' },
        { key: 'university', label: 'University', type: 'text', required: true, csvColumn: 'University' },
        { key: 'yearOfPassing', label: 'Year of Passing', type: 'number', required: true, csvColumn: 'Year of Passing' },
        { key: 'phdStatus', label: 'PhD Status', type: 'select', required: true, csvColumn: 'PhD Status', selectOptions: ['Completed', 'Pursuing', 'Not Applicable'] },
        { key: 'phdAwardedDate', label: 'PhD Awarded Date', type: 'date', required: false, csvColumn: 'PhD Awarded Date' },
      ],
      requiredEvidence: ['Degree Certificate', 'PhD Certificate'],
      validationRules: [
        'Qualification Level must be valid (UG/PG/PhD/Post Doctoral)',
        'Year of Passing must be a valid year',
        'PhD Awarded Date required if PhD Status is Completed',
      ],
      templateFile: '/templates/faculty_qualifications_template.csv',
    },
    {
      id: 'employment-info',
      label: 'Employment Information',
      icon: 'Briefcase',
      fields: [
        { key: 'employmentType', label: 'Employment Type', type: 'select', required: true, csvColumn: 'Employment Type', selectOptions: ['Regular', 'Contract', 'Visiting', 'Adjunct'] },
        { key: 'facultyCategory', label: 'Faculty Category', type: 'select', required: true, csvColumn: 'Faculty Category', selectOptions: ['Full-Time', 'Part-Time'] },
        { key: 'dateOfJoiningInstitution', label: 'Date of Joining Institution', type: 'date', required: true, csvColumn: 'Date of Joining Institution' },
        { key: 'dateOfJoiningProfession', label: 'Date of Joining Profession', type: 'date', required: false, csvColumn: 'Date of Joining Profession' },
        { key: 'totalExperience', label: 'Total Experience (Years)', type: 'number', required: true, csvColumn: 'Total Experience (Years)' },
        { key: 'industryExperience', label: 'Industry Experience (Years)', type: 'number', required: false, csvColumn: 'Industry Experience (Years)' },
        { key: 'aicteFacultyId', label: 'AICTE Faculty ID', type: 'text', required: false, csvColumn: 'AICTE Faculty ID' },
      ],
      requiredEvidence: ['Appointment Order', 'Joining Report', 'Experience Certificates', 'Experience Letters', 'AICTE Records'],
      validationRules: [
        'Employment Type must be valid',
        'Faculty Category must be Full-Time or Part-Time',
        'Total Experience must be >= 0',
        'Date of Joining Institution is required',
      ],
      templateFile: '/templates/faculty_employment_template.csv',
    },
    {
      id: 'fdps',
      label: 'Faculty Development Programs',
      icon: 'Presentation',
      fields: [
        { key: 'fdpName', label: 'FDP Name', type: 'text', required: true, csvColumn: 'FDP Name' },
        { key: 'organizingBody', label: 'Organizing Body', type: 'text', required: true, csvColumn: 'Organizing Body' },
        { key: 'startDate', label: 'Start Date', type: 'date', required: true, csvColumn: 'Start Date' },
        { key: 'endDate', label: 'End Date', type: 'date', required: true, csvColumn: 'End Date' },
        { key: 'durationDays', label: 'Duration Days', type: 'number', required: true, csvColumn: 'Duration Days' },
        { key: 'mode', label: 'Mode', type: 'select', required: true, csvColumn: 'Mode', selectOptions: ['Online', 'Offline'] },
        { key: 'certificationAvailable', label: 'Certification Available', type: 'boolean', required: true, csvColumn: 'Certification Available' },
      ],
      requiredEvidence: ['FDP Certificate', 'Certificate Upload'],
      validationRules: [
        'Start Date must be before End Date',
        'Duration Days must be > 0',
        'Mode must be Online or Offline',
      ],
      templateFile: '/templates/faculty_fdps_template.csv',
    },
    {
      id: 'faculty-documents',
      label: 'Supporting Documents',
      icon: 'FolderOpen',
      fields: [],
      requiredEvidence: ['Appointment Orders', 'Degree Certificates', 'PhD Certificates', 'Experience Certificates', 'FDP Certificates', 'PAN Card', 'Aadhaar'],
      validationRules: [],
      templateFile: '',
    },
  ],
};

// ============ STUDENT REPOSITORY ============
export const studentRepositoryConfig: RepositoryModuleConfig = {
  id: 'student',
  label: 'Student Repository',
  description: 'Manage student records including profiles, admissions, diversity, performance, progression, scholarships, and achievements',
  icon: 'BookOpen',
  color: 'text-emerald-600',
  gradient: 'from-emerald-500 to-emerald-600',
  tabs: [
    {
      id: 'student-profile',
      label: 'Student Profile',
      icon: 'Users',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'studentId', label: 'Student ID', type: 'text', required: true, csvColumn: 'Student ID' },
        { key: 'rollNumber', label: 'Roll Number', type: 'text', required: true, csvColumn: 'Roll Number' },
        { key: 'studentName', label: 'Student Name', type: 'text', required: true, csvColumn: 'Student Name' },
        { key: 'gender', label: 'Gender', type: 'select', required: true, csvColumn: 'Gender', selectOptions: ['Male', 'Female', 'Other'] },
        { key: 'dateOfBirth', label: 'Date of Birth', type: 'date', required: true, csvColumn: 'Date of Birth' },
        { key: 'aadhaarNumber', label: 'Aadhaar Number', type: 'text', required: false, csvColumn: 'Aadhaar Number' },
        { key: 'emailAddress', label: 'Email Address', type: 'text', required: false, csvColumn: 'Email Address' },
        { key: 'mobileNumber', label: 'Mobile Number', type: 'text', required: false, csvColumn: 'Mobile Number' },
        { key: 'academicUnit', label: 'Academic Unit', type: 'select', required: true, csvColumn: 'Academic Unit', masterDataSource: 'departments' },
        { key: 'program', label: 'Program', type: 'select', required: true, csvColumn: 'Program', masterDataSource: 'programOfferings' },
        { key: 'currentSemesterYear', label: 'Current Semester/Year', type: 'number', required: true, csvColumn: 'Current Semester/Year' },
        { key: 'studentStatus', label: 'Student Status', type: 'select', required: true, csvColumn: 'Student Status', selectOptions: ['Active', 'Graduated', 'Discontinued'] },
      ],
      requiredEvidence: ['Admission Register', 'Student Records', 'Admission Form', 'SSC Certificate', 'Aadhaar Card'],
      validationRules: [
        'Student ID must be unique',
        'Roll Number must be unique',
        'Registration Number must be unique',
        'Program must exist in master data',
        'Academic Unit must exist in master data',
      ],
      templateFile: '/templates/student_profile_template.csv',
    },
    {
      id: 'admission-info',
      label: 'Admission Info',
      icon: 'UserPlus',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'admissionYear', label: 'Admission Year', type: 'select', required: true, csvColumn: 'Admission Year', masterDataSource: 'academicYears' },
        { key: 'admissionType', label: 'Admission Type', type: 'select', required: true, csvColumn: 'Admission Type', selectOptions: ['Convener', 'Management', 'Lateral Entry', 'NRI', 'Spot'] },
        { key: 'admissionCategory', label: 'Admission Category', type: 'select', required: true, csvColumn: 'Admission Category', selectOptions: ['General', 'OBC', 'SC', 'ST', 'EWS'] },
        { key: 'admissionRank', label: 'Admission Rank', type: 'number', required: false, csvColumn: 'Admission Rank' },
        { key: 'admissionQuota', label: 'Admission Quota', type: 'select', required: false, csvColumn: 'Admission Quota', selectOptions: ['Convener', 'Management', 'NRI', 'Spot'] },
        { key: 'stateOfOrigin', label: 'State of Origin', type: 'text', required: false, csvColumn: 'State of Origin' },
        { key: 'country', label: 'Country', type: 'text', required: false, csvColumn: 'Country' },
        { key: 'admissionStatus', label: 'Admission Status', type: 'select', required: true, csvColumn: 'Admission Status', selectOptions: ['Admitted', 'Cancelled'] },
      ],
      requiredEvidence: ['Admission Register', 'Admission Records', 'Passport/Visa'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Admission Year must exist in master data',
        'Admission Type must be valid',
        'Admission Category must be valid',
      ],
      templateFile: '/templates/student_admission_info_template.csv',
    },
    {
      id: 'student-diversity',
      label: 'Student Diversity',
      icon: 'Users',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'socialCategory', label: 'Social Category', type: 'select', required: true, csvColumn: 'Social Category', selectOptions: ['General', 'OBC', 'SC', 'ST'] },
        { key: 'economicallyWeakerSection', label: 'Economically Weaker Section', type: 'select', required: false, csvColumn: 'Economically Weaker Section', selectOptions: ['Yes', 'No'] },
        { key: 'minorityStatus', label: 'Minority Status', type: 'select', required: false, csvColumn: 'Minority Status', selectOptions: ['Yes', 'No'] },
        { key: 'differentlyAbled', label: 'Differently Abled', type: 'select', required: false, csvColumn: 'Differently Abled', selectOptions: ['Yes', 'No'] },
        { key: 'nationality', label: 'Nationality', type: 'text', required: false, csvColumn: 'Nationality' },
        { key: 'firstGenerationLearner', label: 'First Generation Learner', type: 'select', required: false, csvColumn: 'First Generation Learner', selectOptions: ['Yes', 'No'] },
      ],
      requiredEvidence: ['Admission Records', 'Student Records', 'Medical Certificate', 'Passport', 'Self Declaration'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Social Category must be valid',
      ],
      templateFile: '/templates/student_diversity_template.csv',
    },
    {
      id: 'academic-performance',
      label: 'Academic Performance',
      icon: 'BarChart3',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'semester', label: 'Semester', type: 'number', required: true, csvColumn: 'Semester' },
        { key: 'sgpa', label: 'SGPA', type: 'number', required: false, csvColumn: 'SGPA' },
        { key: 'cgpa', label: 'CGPA', type: 'number', required: false, csvColumn: 'CGPA' },
        { key: 'backlogCount', label: 'Backlog Count', type: 'number', required: false, csvColumn: 'Backlog Count' },
        { key: 'attendancePercentage', label: 'Attendance Percentage', type: 'number', required: false, csvColumn: 'Attendance Percentage' },
        { key: 'graduationStatus', label: 'Graduation Status', type: 'select', required: false, csvColumn: 'Graduation Status', selectOptions: ['Graduated', 'Continuing'] },
      ],
      requiredEvidence: ['Academic Records', 'Result Records', 'Result Sheet', 'Attendance Records'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Academic Year must exist in master data',
        'Semester must be valid (1-8)',
        'SGPA must be between 0-10',
        'CGPA must be between 0-10',
        'Attendance Percentage must be between 0-100',
      ],
      templateFile: '/templates/student_academic_performance_template.csv',
    },
    {
      id: 'student-progression',
      label: 'Student Progression',
      icon: 'TrendingUp',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'placementStatus', label: 'Placement Status', type: 'select', required: false, csvColumn: 'Placement Status', selectOptions: ['Yes', 'No'] },
        { key: 'higherEducationStatus', label: 'Higher Education Status', type: 'select', required: false, csvColumn: 'Higher Education Status', selectOptions: ['Yes', 'No'] },
        { key: 'competitiveExamQualified', label: 'Competitive Exam Qualified', type: 'select', required: false, csvColumn: 'Competitive Exam Qualified', selectOptions: ['Yes', 'No'] },
        { key: 'entrepreneurshipStatus', label: 'Entrepreneurship Status', type: 'select', required: false, csvColumn: 'Entrepreneurship Status', selectOptions: ['Yes', 'No'] },
        { key: 'internshipCompleted', label: 'Internship Completed', type: 'select', required: false, csvColumn: 'Internship Completed', selectOptions: ['Yes', 'No'] },
      ],
      requiredEvidence: ['Student Records', 'Offer Letter', 'Admission Letter', 'Score Card', 'Registration Proof', 'Internship Certificate'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Academic Year must exist in master data',
      ],
      templateFile: '/templates/student_progression_template.csv',
    },
    {
      id: 'scholarship-financial-support',
      label: 'Scholarship & Financial Support',
      icon: 'Wallet',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'scholarshipName', label: 'Scholarship Name', type: 'text', required: true, csvColumn: 'Scholarship Name' },
        { key: 'scholarshipType', label: 'Scholarship Type', type: 'select', required: true, csvColumn: 'Scholarship Type', selectOptions: ['Government', 'Institutional', 'Private', 'NGO', 'Other'] },
        { key: 'provider', label: 'Provider/Agency', type: 'text', required: true, csvColumn: 'Provider/Agency' },
        { key: 'amount', label: 'Amount (INR)', type: 'number', required: true, csvColumn: 'Amount (INR)' },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'feeWaiverStatus', label: 'Fee Waiver Status', type: 'select', required: false, csvColumn: 'Fee Waiver Status', selectOptions: ['Full Waiver', 'Partial Waiver', 'No Waiver'] },
        { key: 'disbursementStatus', label: 'Disbursement Status', type: 'select', required: true, csvColumn: 'Disbursement Status', selectOptions: ['Disbursed', 'Pending', 'Rejected'] },
      ],
      requiredEvidence: ['Scholarship Letter', 'Disbursement Proof', 'Fee Receipt', 'Sanction Order'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Amount must be > 0',
        'Academic Year must exist in master data',
        'Scholarship Name is required',
      ],
      templateFile: '/templates/student_scholarship_template.csv',
    },
    {
      id: 'student-achievements',
      label: 'Student Achievements',
      icon: 'Trophy',
      fields: [
        { key: 'registrationNumber', label: 'Student Registration Number', type: 'text', required: true, csvColumn: 'Student Registration Number' },
        { key: 'achievementType', label: 'Achievement Type', type: 'select', required: true, csvColumn: 'Achievement Type', selectOptions: ['Hackathon', 'Sports', 'Cultural', 'Paper Presentation', 'Project Competition', 'Olympiad', 'Other'] },
        { key: 'achievementName', label: 'Achievement Name', type: 'text', required: true, csvColumn: 'Achievement Name' },
        { key: 'level', label: 'Level', type: 'select', required: true, csvColumn: 'Level', selectOptions: ['International', 'National', 'State', 'University', 'College'] },
        { key: 'awardPosition', label: 'Award/Position', type: 'text', required: false, csvColumn: 'Award/Position' },
        { key: 'date', label: 'Date', type: 'date', required: true, csvColumn: 'Date' },
        { key: 'academicYear', label: 'Academic Year', type: 'select', required: true, csvColumn: 'Academic Year', masterDataSource: 'academicYears' },
        { key: 'organizingBody', label: 'Organizing Body', type: 'text', required: false, csvColumn: 'Organizing Body' },
      ],
      requiredEvidence: ['Achievement Certificate', 'Event Participation Proof', 'Medal/Trophy Photo', 'Event Report'],
      validationRules: [
        'Registration Number must exist in Student Profile',
        'Date must be valid',
        'Academic Year must exist in master data',
        'Achievement Name is required',
      ],
      templateFile: '/templates/student_achievements_template.csv',
    },
  ],
};

// ============ RESEARCH REPOSITORY ============
export const researchRepositoryConfig: RepositoryModuleConfig = {
  id: 'research',
  label: 'Research Repository',
  description: 'Manage department research records including publications, patents, grants, sponsored projects, and consultancy',
  icon: 'FlaskConical',
  color: 'text-pink-600',
  gradient: 'from-pink-500 to-pink-600',
  tabs: [
    {
      id: 'publications',
      label: 'Publications',
      icon: 'FileText',
      fields: [
        { key: 'publicationTitle', label: 'Publication Title', type: 'text', required: true, csvColumn: 'Publication Title' },
        { key: 'publicationType', label: 'Publication Type', type: 'select', required: true, csvColumn: 'Publication Type', selectOptions: ['Journal', 'Conference', 'Book Chapter'] },
        { key: 'authors', label: 'Authors (Faculty)', type: 'text', required: true, csvColumn: 'Authors' },
        { key: 'studentAuthors', label: 'Student Authors', type: 'text', required: false, csvColumn: 'Student Authors' },
        { key: 'correspondingAuthor', label: 'Corresponding Author', type: 'text', required: false, csvColumn: 'Corresponding Author' },
        { key: 'journalConferenceName', label: 'Journal / Conference Name', type: 'text', required: true, csvColumn: 'Journal / Conference Name' },
        { key: 'publisher', label: 'Publisher', type: 'text', required: false, csvColumn: 'Publisher' },
        { key: 'issnIsbn', label: 'ISSN / ISBN', type: 'text', required: false, csvColumn: 'ISSN / ISBN' },
        { key: 'doi', label: 'DOI', type: 'text', required: false, csvColumn: 'DOI' },
        { key: 'indexedIn', label: 'Indexed In', type: 'text', required: false, csvColumn: 'Indexed In' },
        { key: 'impactFactor', label: 'Impact Factor', type: 'number', required: false, csvColumn: 'Impact Factor' },
        { key: 'citationCount', label: 'Citation Count', type: 'number', required: false, csvColumn: 'Citation Count' },
        { key: 'publicationDate', label: 'Publication Date', type: 'date', required: true, csvColumn: 'Publication Date' },
        { key: 'academicYear', label: 'Academic Year', type: 'text', required: true, csvColumn: 'Academic Year' },
        { key: 'status', label: 'Status', type: 'select', required: true, csvColumn: 'Status', selectOptions: ['Accepted', 'Published'] },
        { key: 'publicationUrl', label: 'Publication URL', type: 'text', required: false, csvColumn: 'Publication URL' },
      ],
      requiredEvidence: ['Publication PDF', 'DOI Link', 'Indexing Proof', 'Journal Proof', 'Scopus/WoS Report', 'Acceptance Letter', 'URL Proof', 'Publication Records'],
      validationRules: [
        'Publication Title is required',
        'At least one Author (Faculty) is required',
        'Journal / Conference Name is required',
        'Publication Date must be valid',
        'Academic Year must be valid',
      ],
      templateFile: '/templates/research_publications_template.csv',
    },
    {
      id: 'patents',
      label: 'Patents',
      icon: 'Shield',
      fields: [
        { key: 'patentTitle', label: 'Patent Title', type: 'text', required: true, csvColumn: 'Patent Title' },
        { key: 'inventors', label: 'Inventors (Faculty)', type: 'text', required: true, csvColumn: 'Inventors' },
        { key: 'studentInventors', label: 'Student Inventors', type: 'text', required: false, csvColumn: 'Student Inventors' },
        { key: 'patentNumber', label: 'Patent Number', type: 'text', required: false, csvColumn: 'Patent Number' },
        { key: 'applicationNumber', label: 'Application Number', type: 'text', required: true, csvColumn: 'Application Number' },
        { key: 'country', label: 'Country', type: 'text', required: true, csvColumn: 'Country' },
        { key: 'filingDate', label: 'Filing Date', type: 'date', required: true, csvColumn: 'Filing Date' },
        { key: 'publicationDate', label: 'Publication Date', type: 'date', required: false, csvColumn: 'Publication Date' },
        { key: 'grantDate', label: 'Grant Date', type: 'date', required: false, csvColumn: 'Grant Date' },
        { key: 'patentStatus', label: 'Patent Status', type: 'select', required: true, csvColumn: 'Patent Status', selectOptions: ['Filed', 'Published', 'Granted'] },
        { key: 'commercialized', label: 'Commercialized', type: 'select', required: false, csvColumn: 'Commercialized', selectOptions: ['Yes', 'No'] },
        { key: 'revenueGenerated', label: 'Revenue Generated', type: 'number', required: false, csvColumn: 'Revenue Generated' },
      ],
      requiredEvidence: ['Patent Certificate', 'Patent Filing Receipt', 'Filing Receipt', 'Patent Records', 'Patent Publication', 'Commercialization Agreement', 'Revenue Proof'],
      validationRules: [
        'Patent Title is required',
        'At least one Inventor (Faculty) is required',
        'Application Number must be unique',
        'Country is required',
        'Filing Date must be valid',
      ],
      templateFile: '/templates/research_patents_template.csv',
    },
    {
      id: 'research-grants',
      label: 'Research Grants',
      icon: 'Banknote',
      fields: [
        { key: 'grantTitle', label: 'Grant Title', type: 'text', required: true, csvColumn: 'Grant Title' },
        { key: 'fundingAgency', label: 'Funding Agency', type: 'text', required: true, csvColumn: 'Funding Agency' },
        { key: 'principalInvestigator', label: 'Principal Investigator', type: 'text', required: true, csvColumn: 'Principal Investigator' },
        { key: 'coInvestigators', label: 'Co-Investigators', type: 'text', required: false, csvColumn: 'Co-Investigators' },
        { key: 'grantCategory', label: 'Grant Category', type: 'select', required: true, csvColumn: 'Grant Category', selectOptions: ['Government', 'Industry', 'International'] },
        { key: 'amountSanctioned', label: 'Amount Sanctioned', type: 'number', required: true, csvColumn: 'Amount Sanctioned' },
        { key: 'amountReceived', label: 'Amount Received', type: 'number', required: false, csvColumn: 'Amount Received' },
        { key: 'startDate', label: 'Start Date', type: 'date', required: true, csvColumn: 'Start Date' },
        { key: 'endDate', label: 'End Date', type: 'date', required: false, csvColumn: 'End Date' },
        { key: 'status', label: 'Status', type: 'select', required: true, csvColumn: 'Status', selectOptions: ['Ongoing', 'Completed'] },
      ],
      requiredEvidence: ['Sanction Letter', 'Grant Records', 'Grant Approval', 'Financial Records', 'Completion Report'],
      validationRules: [
        'Grant Title is required',
        'Funding Agency is required',
        'Principal Investigator must exist in Faculty',
        'Amount Sanctioned must be > 0',
        'Start Date must be valid',
      ],
      templateFile: '/templates/research_grants_template.csv',
    },
    {
      id: 'sponsored-projects',
      label: 'Sponsored Projects',
      icon: 'FolderKanban',
      fields: [
        { key: 'projectTitle', label: 'Project Title', type: 'text', required: true, csvColumn: 'Project Title' },
        { key: 'sponsorOrganization', label: 'Sponsor Organization', type: 'text', required: true, csvColumn: 'Sponsor Organization' },
        { key: 'principalInvestigator', label: 'Principal Investigator', type: 'text', required: true, csvColumn: 'Principal Investigator' },
        { key: 'coInvestigators', label: 'Co-Investigators', type: 'text', required: false, csvColumn: 'Co-Investigators' },
        { key: 'projectValue', label: 'Project Value', type: 'number', required: true, csvColumn: 'Project Value' },
        { key: 'startDate', label: 'Start Date', type: 'date', required: true, csvColumn: 'Start Date' },
        { key: 'endDate', label: 'End Date', type: 'date', required: false, csvColumn: 'End Date' },
        { key: 'projectStatus', label: 'Project Status', type: 'select', required: true, csvColumn: 'Project Status', selectOptions: ['Ongoing', 'Completed'] },
        { key: 'projectOutcome', label: 'Project Outcome', type: 'text', required: false, csvColumn: 'Project Outcome' },
      ],
      requiredEvidence: ['Project Approval', 'Agreement', 'Project Records', 'Financial Records', 'Completion Report'],
      validationRules: [
        'Project Title is required',
        'Sponsor Organization is required',
        'Principal Investigator must exist in Faculty',
        'Project Value must be > 0',
        'Start Date must be valid',
      ],
      templateFile: '/templates/research_sponsored_projects_template.csv',
    },
    {
      id: 'consultancy-projects',
      label: 'Consultancy Projects',
      icon: 'Briefcase',
      fields: [
        { key: 'consultancyTitle', label: 'Consultancy Title', type: 'text', required: true, csvColumn: 'Consultancy Title' },
        { key: 'clientOrganization', label: 'Client Organization', type: 'text', required: true, csvColumn: 'Client Organization' },
        { key: 'facultyLead', label: 'Faculty Lead', type: 'text', required: true, csvColumn: 'Faculty Lead' },
        { key: 'teamMembers', label: 'Team Members', type: 'text', required: false, csvColumn: 'Team Members' },
        { key: 'consultancyValue', label: 'Consultancy Value', type: 'number', required: true, csvColumn: 'Consultancy Value' },
        { key: 'startDate', label: 'Start Date', type: 'date', required: true, csvColumn: 'Start Date' },
        { key: 'endDate', label: 'End Date', type: 'date', required: false, csvColumn: 'End Date' },
        { key: 'status', label: 'Status', type: 'select', required: true, csvColumn: 'Status', selectOptions: ['Active', 'Completed'] },
        { key: 'outcomeSummary', label: 'Outcome Summary', type: 'text', required: false, csvColumn: 'Outcome Summary' },
      ],
      requiredEvidence: ['Consultancy Agreement', 'Consultancy Records', 'Invoice', 'Completion Report'],
      validationRules: [
        'Consultancy Title is required',
        'Client Organization is required',
        'Faculty Lead must exist in Faculty',
        'Consultancy Value must be > 0',
        'Start Date must be valid',
      ],
      templateFile: '/templates/research_consultancy_projects_template.csv',
    },
  ],
};

// All repository configs
export const allRepositoryConfigs: RepositoryModuleConfig[] = [
  academicRepositoryConfig,
  facultyRepositoryConfig,
  studentRepositoryConfig,
  researchRepositoryConfig,
];

// ============ MOCK DATA ============

// Dashboard KPIs
export const dashboardKPIs: KPICard[] = [
  { id: 'academic-completion', label: 'Academic Repository', value: 78, suffix: '%', icon: 'GraduationCap', color: 'text-violet-600 bg-violet-500/10', trend: 5, trendLabel: 'vs last month' },
  { id: 'faculty-completion', label: 'Faculty Repository', value: 85, suffix: '%', icon: 'Users', color: 'text-indigo-600 bg-indigo-500/10', trend: 3, trendLabel: 'vs last month' },
  { id: 'student-completion', label: 'Student Repository', value: 72, suffix: '%', icon: 'BookOpen', color: 'text-emerald-600 bg-emerald-500/10', trend: 8, trendLabel: 'vs last month' },
  { id: 'research-completion', label: 'Research Repository', value: 65, suffix: '%', icon: 'FlaskConical', color: 'text-pink-600 bg-pink-500/10', trend: 4, trendLabel: 'vs last month' },
  { id: 'pending-reviews', label: 'Pending Reviews', value: 14, icon: 'Clock', color: 'text-orange-600 bg-orange-500/10', trend: -3, trendLabel: 'vs last week' },
  { id: 'pending-verification', label: 'Pending Verification', value: 8, icon: 'Shield', color: 'text-cyan-600 bg-cyan-500/10', trend: -2, trendLabel: 'cleared' },
  { id: 'pending-evidence', label: 'Pending Evidence', value: 12, icon: 'FileText', color: 'text-amber-600 bg-amber-500/10', trend: -4, trendLabel: 'uploaded' },
  { id: 'readiness', label: 'Readiness Score', value: 76, suffix: '%', icon: 'Target', color: 'text-green-600 bg-green-500/10', trend: 5.3, trendLabel: 'improvement' },
];

// Repository Health Metrics
export const repositoryHealth: Record<string, RepositoryMetrics> = {
  academic: { dataCompleteness: 86, evidenceCompleteness: 72, verificationPercent: 78, readinessScore: 79 },
  faculty: { dataCompleteness: 92, evidenceCompleteness: 68, verificationPercent: 85, readinessScore: 82 },
  student: { dataCompleteness: 88, evidenceCompleteness: 75, verificationPercent: 70, readinessScore: 78 },
  research: { dataCompleteness: 74, evidenceCompleteness: 60, verificationPercent: 65, readinessScore: 66 },
};

// Repository Summaries per tab
export const repositorySummaries: Record<string, RepositorySummary> = {
  // Academic
  'curriculum': { recordsUploaded: 8, pendingValidation: 1, pendingVerification: 2, verified: 4, approved: 4, rejected: 0, lastUpdated: '2025-01-08 10:15' },
  'courses': { recordsUploaded: 156, pendingValidation: 5, pendingVerification: 12, verified: 130, approved: 125, rejected: 4, lastUpdated: '2025-01-12 16:45' },
  'academic-calendar': { recordsUploaded: 4, pendingValidation: 0, pendingVerification: 0, verified: 4, approved: 4, rejected: 0, lastUpdated: '2025-01-05 09:00' },
  'value-added-courses': { recordsUploaded: 12, pendingValidation: 2, pendingVerification: 3, verified: 5, approved: 5, rejected: 1, lastUpdated: '2025-01-09 11:20' },
  'moocs': { recordsUploaded: 24, pendingValidation: 4, pendingVerification: 6, verified: 10, approved: 10, rejected: 2, lastUpdated: '2025-01-11 13:40' },
  'supporting-documents': { recordsUploaded: 45, pendingValidation: 3, pendingVerification: 8, verified: 28, approved: 25, rejected: 2, lastUpdated: '2025-01-12 15:00' },
  // Faculty
  'faculty-profiles': { recordsUploaded: 42, pendingValidation: 0, pendingVerification: 2, verified: 38, approved: 38, rejected: 0, lastUpdated: '2025-01-11 09:30' },
  'qualifications': { recordsUploaded: 86, pendingValidation: 3, pendingVerification: 5, verified: 72, approved: 70, rejected: 1, lastUpdated: '2025-01-10 14:00' },
  'employment-info': { recordsUploaded: 42, pendingValidation: 1, pendingVerification: 3, verified: 35, approved: 34, rejected: 0, lastUpdated: '2025-01-11 09:30' },
  'fdps': { recordsUploaded: 28, pendingValidation: 1, pendingVerification: 3, verified: 20, approved: 18, rejected: 2, lastUpdated: '2025-01-08 11:45' },
  'faculty-documents': { recordsUploaded: 52, pendingValidation: 4, pendingVerification: 6, verified: 36, approved: 34, rejected: 2, lastUpdated: '2025-01-12 13:00' },
  // Student
  'student-profile': { recordsUploaded: 856, pendingValidation: 5, pendingVerification: 12, verified: 820, approved: 815, rejected: 4, lastUpdated: '2025-01-12 08:00' },
  'admission-info': { recordsUploaded: 240, pendingValidation: 3, pendingVerification: 8, verified: 220, approved: 218, rejected: 2, lastUpdated: '2025-01-11 10:30' },
  'student-diversity': { recordsUploaded: 856, pendingValidation: 2, pendingVerification: 6, verified: 830, approved: 825, rejected: 3, lastUpdated: '2025-01-11 14:00' },
  'academic-performance': { recordsUploaded: 3200, pendingValidation: 15, pendingVerification: 45, verified: 3000, approved: 2980, rejected: 10, lastUpdated: '2025-01-12 16:00' },
  'student-progression': { recordsUploaded: 320, pendingValidation: 4, pendingVerification: 10, verified: 280, approved: 275, rejected: 6, lastUpdated: '2025-01-11 15:30' },
  'scholarship-financial-support': { recordsUploaded: 145, pendingValidation: 3, pendingVerification: 8, verified: 120, approved: 115, rejected: 4, lastUpdated: '2025-01-09 14:30' },
  'student-achievements': { recordsUploaded: 68, pendingValidation: 4, pendingVerification: 8, verified: 48, approved: 45, rejected: 3, lastUpdated: '2025-01-10 12:00' },
  // Research
  'publications': { recordsUploaded: 78, pendingValidation: 3, pendingVerification: 8, verified: 58, approved: 55, rejected: 4, lastUpdated: '2025-01-12 15:30' },
  'patents': { recordsUploaded: 12, pendingValidation: 1, pendingVerification: 2, verified: 8, approved: 7, rejected: 1, lastUpdated: '2025-01-10 09:00' },
  'research-grants': { recordsUploaded: 18, pendingValidation: 2, pendingVerification: 3, verified: 10, approved: 10, rejected: 0, lastUpdated: '2025-01-09 11:00' },
  'sponsored-projects': { recordsUploaded: 11, pendingValidation: 0, pendingVerification: 2, verified: 8, approved: 7, rejected: 1, lastUpdated: '2025-01-07 16:00' },
  'consultancy-projects': { recordsUploaded: 8, pendingValidation: 1, pendingVerification: 2, verified: 4, approved: 4, rejected: 0, lastUpdated: '2025-01-08 14:00' },
};

// Upload History
export const uploadHistory: UploadHistoryRecord[] = [
  { id: '1', fileName: 'faculty_profiles_cse_2025.csv', tab: 'Faculty Profiles', repository: 'faculty', uploadedAt: '2025-01-11 09:30', recordsCount: 42, validRecords: 42, invalidRecords: 0, status: 'approved', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'approved' },
  { id: '2', fileName: 'courses_sem1_2025.csv', tab: 'Courses', repository: 'academic', uploadedAt: '2025-01-12 16:45', recordsCount: 42, validRecords: 40, invalidRecords: 2, status: 'approved', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'approved' },
  { id: '3', fileName: 'student_enrollment_2025.csv', tab: 'Student Profile', repository: 'student', uploadedAt: '2025-01-12 08:00', recordsCount: 240, validRecords: 238, invalidRecords: 2, status: 'approved', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'approved' },
  { id: '4', fileName: 'publications_2024_25.csv', tab: 'Publications', repository: 'research', uploadedAt: '2025-01-12 15:30', recordsCount: 28, validRecords: 27, invalidRecords: 1, status: 'pending', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'hod_review' },
  { id: '5', fileName: 'vac_2025_26.csv', tab: 'Value Added Courses', repository: 'academic', uploadedAt: '2025-01-09 11:20', recordsCount: 12, validRecords: 11, invalidRecords: 1, status: 'approved', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'approved' },
  { id: '6', fileName: 'student_results_sem5.csv', tab: 'Academic Performance', repository: 'student', uploadedAt: '2025-01-12 16:00', recordsCount: 180, validRecords: 178, invalidRecords: 2, status: 'pending', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'iqac_verification' },
  { id: '7', fileName: 'curriculum_r22_2025.csv', tab: 'Curriculum', repository: 'academic', uploadedAt: '2025-01-08 10:15', recordsCount: 8, validRecords: 8, invalidRecords: 0, status: 'approved', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'approved' },
  { id: '8', fileName: 'moocs_2024_25.csv', tab: 'MOOCs', repository: 'academic', uploadedAt: '2025-01-11 13:40', recordsCount: 24, validRecords: 22, invalidRecords: 2, status: 'pending', uploadedBy: 'Dr. Anita Sharma', workflowStatus: 'hod_review' },
];

// Evidence Documents
export const evidenceDocuments: EvidenceDocument[] = [
  { id: '1', name: 'Curriculum Structure R22.pdf', category: 'Curriculum', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-08', status: 'verified', fileType: 'pdf', size: '2.4 MB' },
  { id: '2', name: 'BoS Minutes Dec 2024.pdf', category: 'Curriculum', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-06', status: 'verified', fileType: 'pdf', size: '1.8 MB' },
  { id: '3', name: 'Academic Calendar 2025-26.pdf', category: 'Academic Calendar', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-05', status: 'verified', fileType: 'pdf', size: '1.2 MB' },
  { id: '4', name: 'Course Syllabus CSE AI.pdf', category: 'Courses', version: 'v2.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-12', status: 'pending', fileType: 'pdf', size: '4.5 MB' },
  { id: '5', name: 'NPTEL Completion Reports.zip', category: 'MOOCs', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-10', status: 'pending', fileType: 'zip', size: '15.6 MB' },
  { id: '6', name: 'VAC Certificates Bundle.zip', category: 'Value Added Courses', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-09', status: 'verified', fileType: 'zip', size: '8.2 MB' },
  { id: '7', name: 'Regulation R22 Document.pdf', category: 'Academic Regulations', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-04', status: 'verified', fileType: 'pdf', size: '3.1 MB' },
  { id: '8', name: 'Faculty Appointment Orders.zip', category: 'Faculty Profiles', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-07', status: 'verified', fileType: 'zip', size: '6.8 MB' },
  { id: '9', name: 'Research Publications 2024.zip', category: 'Publications', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-12', status: 'pending', fileType: 'zip', size: '22.4 MB' },
  { id: '10', name: 'Student Results Sem 5.pdf', category: 'Academic Performance', version: 'v1.0', uploadedBy: 'Dr. Anita Sharma', uploadedDate: '2025-01-12', status: 'pending', fileType: 'pdf', size: '5.2 MB' },
];

// Workflow Steps
export const workflowSteps: WorkflowStep[] = [
  { id: 'draft', label: 'Draft', status: 'completed', timestamp: '2025-01-05 09:00', actor: 'System' },
  { id: 'submitted', label: 'Submitted', status: 'completed', timestamp: '2025-01-05 14:30', actor: 'Coordinator' },
  { id: 'validated', label: 'Validated', status: 'completed', timestamp: '2025-01-06 10:00', actor: 'System' },
  { id: 'evidence', label: 'Evidence Uploaded', status: 'completed', timestamp: '2025-01-06 15:00', actor: 'Coordinator' },
  { id: 'hod-review', label: 'HOD Review', status: 'completed', timestamp: '2025-01-07 10:00', actor: 'HOD' },
  { id: 'iqac-verification', label: 'IQAC Verification', status: 'current', timestamp: '2025-01-10 16:00', actor: 'IQAC Coordinator' },
  { id: 'approved', label: 'Approved', status: 'pending' },
];

// Mock Validation Result
export const mockValidationResult: ValidationResult = {
  totalRows: 42,
  validRows: 40,
  invalidRows: 2,
  warnings: 3,
  errors: [
    { row: 15, column: 'Credits', value: 'abc', message: 'Expected numeric value for Credits', severity: 'error' },
    { row: 28, column: 'Course Code', value: '', message: 'Required field "Course Code" is empty', severity: 'error' },
    { row: 8, column: 'Theory Hours', value: '0', message: 'Theory Hours is 0 - please verify', severity: 'warning' },
    { row: 22, column: 'Program', value: 'B.Sc CSE', message: 'Program "B.Sc CSE" not found in master data', severity: 'error' },
    { row: 35, column: 'Lab Hours', value: '10', message: 'Lab Hours exceeds typical range', severity: 'warning' },
  ],
};