export interface StudentDevFieldConfig {
  key: string;
  label: string;
  type: 'text' | 'number' | 'date' | 'select' | 'currency' | 'percentage';
  required?: boolean;
  options?: string[];
  placeholder?: string;
}

export interface StudentDevTabConfig {
  id: string;
  label: string;
  icon: string;
  description: string;
  fields: StudentDevFieldConfig[];
  sampleData: Record<string, string | number>[];
}

export const studentDevTabConfigs: StudentDevTabConfig[] = [
  {
    id: 'nss',
    label: 'NSS',
    icon: 'Heart',
    description: 'National Service Scheme unit details, activities, and volunteer records',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true, placeholder: '2023-24' },
      { key: 'nssUnitNumber', label: 'NSS Unit Number', type: 'text', required: true },
      { key: 'programmeOfficer', label: 'Programme Officer', type: 'text', required: true },
      { key: 'volunteersEnrolled', label: 'Volunteers Enrolled', type: 'number', required: true },
      { key: 'activitiesConducted', label: 'Activities Conducted', type: 'number' },
      { key: 'hoursCompleted', label: 'Hours Completed', type: 'number' },
      { key: 'villagesAdopted', label: 'Villages Adopted', type: 'text' },
      { key: 'specialCampDetails', label: 'Special Camp Details', type: 'text' },
      { key: 'beneficiaries', label: 'Beneficiaries', type: 'number' },
      { key: 'sdgsAddressed', label: 'SDGs Addressed', type: 'text', placeholder: 'SDG 3, SDG 4, SDG 6' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Attendance', 'Photos', 'Reports', 'Certificates', 'All'] },
      { key: 'framework', label: 'Framework', type: 'select', options: ['NAAC', 'NIRF (Outreach)', 'AISHE', 'Multiple'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Completed', 'Planned'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { academicYear: '2023-24', nssUnitNumber: 'NSS Unit 1', programmeOfficer: 'Dr. Ramesh Patil', volunteersEnrolled: 150, activitiesConducted: 24, hoursCompleted: 1200, villagesAdopted: 'Kothur, Shamshabad', specialCampDetails: '7-day camp at Kothur village', beneficiaries: 2500, sdgsAddressed: 'SDG 3, SDG 4, SDG 6', evidenceType: 'All', framework: 'Multiple', status: 'Completed', remarks: 'Best NSS Unit Award' },
      { academicYear: '2023-24', nssUnitNumber: 'NSS Unit 2', programmeOfficer: 'Prof. Sunita Rao', volunteersEnrolled: 120, activitiesConducted: 18, hoursCompleted: 960, villagesAdopted: 'Medchal, Kompally', specialCampDetails: '7-day camp at Medchal', beneficiaries: 1800, sdgsAddressed: 'SDG 1, SDG 2, SDG 5', evidenceType: 'All', framework: 'NAAC', status: 'Completed', remarks: '' },
      { academicYear: '2024-25', nssUnitNumber: 'NSS Unit 1', programmeOfficer: 'Dr. Ramesh Patil', volunteersEnrolled: 160, activitiesConducted: 8, hoursCompleted: 480, villagesAdopted: 'Kothur, Shamshabad, Ibrahimpatnam', specialCampDetails: 'Planned for Jan 2025', beneficiaries: 900, sdgsAddressed: 'SDG 3, SDG 6, SDG 11', evidenceType: 'Attendance', framework: 'Multiple', status: 'Active', remarks: 'Ongoing activities' },
    ],
  },
  {
    id: 'ncc',
    label: 'NCC',
    icon: 'Shield',
    description: 'National Cadet Corps unit details, camps, and cadet achievements',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true, placeholder: '2023-24' },
      { key: 'nccUnit', label: 'NCC Unit', type: 'text', required: true },
      { key: 'officer', label: 'Associate NCC Officer', type: 'text', required: true },
      { key: 'cadetsEnrolled', label: 'Cadets Enrolled', type: 'number', required: true },
      { key: 'wing', label: 'Army/Navy/Air Wing', type: 'select', required: true, options: ['Army', 'Navy', 'Air Force'] },
      { key: 'camps', label: 'Camps Attended', type: 'text' },
      { key: 'bCertificates', label: 'B Certificates Issued', type: 'number' },
      { key: 'cCertificates', label: 'C Certificates Issued', type: 'number' },
      { key: 'republicDayCamp', label: 'Republic Day Camp', type: 'select', options: ['Selected', 'Not Selected', 'N/A'] },
      { key: 'achievements', label: 'Achievements', type: 'text' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Certificates', 'Camp Reports', 'Photos', 'All'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Completed'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { academicYear: '2023-24', nccUnit: '7 (T) BN NCC', officer: 'Capt. Suresh Reddy', cadetsEnrolled: 100, wing: 'Army', camps: 'CATC, ATC, NIC', bCertificates: 35, cCertificates: 20, republicDayCamp: 'Selected', achievements: '2 cadets selected for RDC Delhi', evidenceType: 'All', status: 'Completed', remarks: 'Best NCC Unit in state' },
      { academicYear: '2023-24', nccUnit: 'Naval Wing Unit', officer: 'Lt. Priya Menon', cadetsEnrolled: 50, wing: 'Navy', camps: 'Naval Camp Vizag, CATC', bCertificates: 18, cCertificates: 8, republicDayCamp: 'Not Selected', achievements: 'Best Cadet Award - Naval Wing', evidenceType: 'Certificates', status: 'Completed', remarks: '' },
      { academicYear: '2024-25', nccUnit: '7 (T) BN NCC', officer: 'Capt. Suresh Reddy', cadetsEnrolled: 110, wing: 'Army', camps: 'CATC (Oct 2024)', bCertificates: 0, cCertificates: 0, republicDayCamp: 'N/A', achievements: '', evidenceType: 'Photos', status: 'Active', remarks: 'Enrollment in progress' },
    ],
  },
  {
    id: 'sports-activities',
    label: 'Sports Activities',
    icon: 'Trophy',
    description: 'Sports events, participants, winners, and achievements at various levels',
    fields: [
      { key: 'academicYear', label: 'Academic Year', type: 'text', required: true },
      { key: 'sport', label: 'Sport', type: 'text', required: true },
      { key: 'event', label: 'Event/Tournament', type: 'text', required: true },
      { key: 'level', label: 'Level', type: 'select', required: true, options: ['University', 'State', 'National', 'International', 'Inter-College', 'Zonal'] },
      { key: 'participants', label: 'No. of Participants', type: 'number' },
      { key: 'winners', label: 'Winners', type: 'text' },
      { key: 'medals', label: 'Medals', type: 'text', placeholder: 'Gold: 2, Silver: 1, Bronze: 3' },
      { key: 'coach', label: 'Coach', type: 'text' },
      { key: 'venue', label: 'Venue', type: 'text' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Certificates', 'Photos', 'Results', 'All'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { academicYear: '2023-24', sport: 'Cricket', event: 'Inter-University Cricket Tournament', level: 'University', participants: 15, winners: 'Team - Runners Up', medals: 'Silver: 1 (Team)', coach: 'Mr. Venkat Rao', venue: 'Osmania University Grounds', date: '2024-02-15', evidenceType: 'All', remarks: 'Best batsman award to Rahul K.' },
      { academicYear: '2023-24', sport: 'Athletics', event: 'State Athletics Championship', level: 'State', participants: 8, winners: 'Priya S. - 100m, Karthik R. - Long Jump', medals: 'Gold: 1, Silver: 1, Bronze: 2', coach: 'Mr. Srinivas', venue: 'Gachibowli Stadium', date: '2024-01-20', evidenceType: 'Certificates', remarks: '2 qualified for nationals' },
      { academicYear: '2023-24', sport: 'Badminton', event: 'National Inter-College Badminton', level: 'National', participants: 4, winners: 'Sneha M. - Singles Quarter-final', medals: '', coach: 'Ms. Lakshmi', venue: 'Indira Gandhi Stadium, Delhi', date: '2024-03-10', evidenceType: 'All', remarks: 'First time at nationals' },
      { academicYear: '2023-24', sport: 'Kabaddi', event: 'South Zone Inter-University', level: 'Zonal', participants: 12, winners: 'Team - Winners', medals: 'Gold: 1 (Team)', coach: 'Mr. Raju Naik', venue: 'SRM University, Chennai', date: '2023-12-05', evidenceType: 'Results', remarks: 'Qualified for All India' },
    ],
  },
  {
    id: 'cultural-activities',
    label: 'Cultural Activities',
    icon: 'Music',
    description: 'Cultural events, performances, competitions, and achievements',
    fields: [
      { key: 'eventName', label: 'Event Name', type: 'text', required: true },
      { key: 'eventType', label: 'Type', type: 'select', required: true, options: ['Dance', 'Music', 'Drama/Theatre', 'Literary', 'Fine Arts', 'Photography', 'Film Making', 'Fashion Show', 'Debate', 'Quiz', 'Fest', 'Other'] },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'participants', label: 'No. of Participants', type: 'number' },
      { key: 'winners', label: 'Winners', type: 'text' },
      { key: 'organizingDepartment', label: 'Organizing Department', type: 'text' },
      { key: 'level', label: 'Level', type: 'select', options: ['Department', 'College', 'Inter-College', 'University', 'State', 'National'] },
      { key: 'chiefGuest', label: 'Chief Guest', type: 'text' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Brochure', 'Photos', 'Certificates', 'All'] },
      { key: 'budget', label: 'Budget (₹)', type: 'currency' },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Upcoming', 'Cancelled'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { eventName: 'Tarang 2024 - Annual Cultural Fest', eventType: 'Fest', date: '2024-03-15', participants: 1200, winners: 'Multiple categories', organizingDepartment: 'Student Affairs', level: 'Inter-College', chiefGuest: 'Padma Shri Anup Jalota', evidenceType: 'All', budget: 800000, status: 'Completed', remarks: '25 colleges participated' },
      { eventName: 'Classical Dance Competition', eventType: 'Dance', date: '2024-01-25', participants: 45, winners: 'Meera K. (Bharatanatyam), Ravi S. (Kuchipudi)', organizingDepartment: 'Cultural Committee', level: 'College', chiefGuest: 'Dr. Padma Subrahmanyam', evidenceType: 'Photos', budget: 50000, status: 'Completed', remarks: 'Winners sent to university level' },
      { eventName: 'Inter-College Debate Championship', eventType: 'Debate', date: '2024-02-10', participants: 60, winners: 'Arun V. - Best Speaker, Team A - Winners', organizingDepartment: 'English Department', level: 'Inter-College', chiefGuest: 'Justice K. Rama Rao (Retd.)', evidenceType: 'Certificates', budget: 30000, status: 'Completed', remarks: '15 colleges participated' },
      { eventName: 'Short Film Festival', eventType: 'Film Making', date: '2024-04-05', participants: 25, winners: 'Team Pixel - Best Film', organizingDepartment: 'Media Club', level: 'College', chiefGuest: 'Director Nag Ashwin', evidenceType: 'All', budget: 75000, status: 'Completed', remarks: '12 short films screened' },
    ],
  },
  {
    id: 'extension-activities',
    label: 'Extension Activities',
    icon: 'HandHeart',
    description: 'Community service, outreach programs, and extension activities',
    fields: [
      { key: 'activity', label: 'Activity Name', type: 'text', required: true },
      { key: 'category', label: 'Category', type: 'select', required: true, options: ['Health Awareness', 'Environmental', 'Education', 'Social Welfare', 'Rural Development', 'Digital Literacy', 'Women Empowerment', 'Skill Development', 'Other'] },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'communityServed', label: 'Community Served', type: 'text', required: true },
      { key: 'beneficiaries', label: 'No. of Beneficiaries', type: 'number', required: true },
      { key: 'facultyCoordinator', label: 'Faculty Coordinator', type: 'text', required: true },
      { key: 'studentsParticipated', label: 'Students Participated', type: 'number' },
      { key: 'collaboratingOrg', label: 'Collaborating Organization', type: 'text' },
      { key: 'sdgsAddressed', label: 'SDGs Addressed', type: 'text' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Reports', 'Photos', 'Feedback', 'All'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Ongoing', 'Planned'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { activity: 'Digital Literacy Camp for Rural Youth', category: 'Digital Literacy', date: '2024-02-20', communityServed: 'Kothur Village Youth', beneficiaries: 150, facultyCoordinator: 'Dr. Anand Kumar', studentsParticipated: 30, collaboratingOrg: 'Digital India Foundation', sdgsAddressed: 'SDG 4, SDG 9', evidenceType: 'All', status: 'Completed', remarks: 'Taught basic computer skills' },
      { activity: 'Women Health Awareness Drive', category: 'Health Awareness', date: '2024-03-08', communityServed: 'Medchal Municipality Women', beneficiaries: 300, facultyCoordinator: 'Dr. Sunita Sharma', studentsParticipated: 45, collaboratingOrg: 'Apollo Foundation', sdgsAddressed: 'SDG 3, SDG 5', evidenceType: 'All', status: 'Completed', remarks: 'Free health checkup provided' },
      { activity: 'Tree Plantation Drive', category: 'Environmental', date: '2024-06-05', communityServed: 'Campus & Surrounding Areas', beneficiaries: 500, facultyCoordinator: 'Prof. Ravi Teja', studentsParticipated: 200, collaboratingOrg: 'Haritha Haram', sdgsAddressed: 'SDG 13, SDG 15', evidenceType: 'Photos', status: 'Completed', remarks: '1000 saplings planted' },
      { activity: 'Skill Development Workshop for School Students', category: 'Skill Development', date: '2024-04-15', communityServed: 'Government School Students', beneficiaries: 80, facultyCoordinator: 'Dr. Priya Nair', studentsParticipated: 20, collaboratingOrg: 'Pratham Education Foundation', sdgsAddressed: 'SDG 4, SDG 8', evidenceType: 'Reports', status: 'Completed', remarks: 'Science experiments & robotics' },
    ],
  },
  {
    id: 'community-outreach',
    label: 'Community Outreach',
    icon: 'Users',
    description: 'Blood donation, plantation, Swachh Bharat, health camps, and literacy programs',
    fields: [
      { key: 'programName', label: 'Program Name', type: 'text', required: true },
      { key: 'programType', label: 'Program Type', type: 'select', required: true, options: ['Blood Donation', 'Plantation', 'Swachh Bharat', 'Health Camp', 'Literacy Program', 'Awareness Campaign', 'Relief Work', 'Other'] },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'location', label: 'Location', type: 'text', required: true },
      { key: 'organizer', label: 'Organizer', type: 'text' },
      { key: 'studentsParticipated', label: 'Students Participated', type: 'number' },
      { key: 'facultyParticipated', label: 'Faculty Participated', type: 'number' },
      { key: 'beneficiaries', label: 'Beneficiaries', type: 'number' },
      { key: 'collaboratingOrg', label: 'Collaborating Organization', type: 'text' },
      { key: 'outcome', label: 'Outcome', type: 'text' },
      { key: 'evidenceType', label: 'Evidence', type: 'select', options: ['Photos', 'Reports', 'Certificates', 'Media Coverage', 'All'] },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Upcoming', 'Cancelled'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { programName: 'Mega Blood Donation Camp', programType: 'Blood Donation', date: '2024-01-26', location: 'College Auditorium', organizer: 'NSS Unit & Red Cross', studentsParticipated: 350, facultyParticipated: 25, beneficiaries: 280, collaboratingOrg: 'Indian Red Cross Society', outcome: '280 units collected', evidenceType: 'All', status: 'Completed', remarks: 'Republic Day special drive' },
      { programName: 'Swachh Campus Abhiyan', programType: 'Swachh Bharat', date: '2024-10-02', location: 'Campus & Surrounding Areas', organizer: 'NSS & Eco Club', studentsParticipated: 500, facultyParticipated: 40, beneficiaries: 1000, collaboratingOrg: 'Municipal Corporation', outcome: '5 km area cleaned', evidenceType: 'Photos', status: 'Completed', remarks: 'Gandhi Jayanti initiative' },
      { programName: 'Free Health Camp for Villagers', programType: 'Health Camp', date: '2024-02-14', location: 'Kothur PHC', organizer: 'NSS Unit 1', studentsParticipated: 60, facultyParticipated: 8, beneficiaries: 450, collaboratingOrg: 'Apollo Hospitals', outcome: '450 patients treated, 50 referrals', evidenceType: 'Reports', status: 'Completed', remarks: 'Eye, dental, general checkup' },
      { programName: 'Plantation Drive - Green Campus', programType: 'Plantation', date: '2024-07-01', location: 'College Campus', organizer: 'Eco Club & NCC', studentsParticipated: 200, facultyParticipated: 15, beneficiaries: 2000, collaboratingOrg: 'Forest Department', outcome: '500 saplings planted', evidenceType: 'Photos', status: 'Completed', remarks: 'Van Mahotsav celebration' },
    ],
  },
  {
    id: 'clubs',
    label: 'Clubs & Professional Societies',
    icon: 'Layers',
    description: 'Student clubs, technical societies, and their activities',
    fields: [
      { key: 'clubName', label: 'Club/Society Name', type: 'text', required: true },
      { key: 'clubType', label: 'Type', type: 'select', required: true, options: ['Technical', 'Cultural', 'Literary', 'Social Service', 'Sports', 'Professional Society', 'Innovation', 'Other'] },
      { key: 'facultyCoordinator', label: 'Faculty Coordinator', type: 'text', required: true },
      { key: 'studentPresident', label: 'Student President', type: 'text' },
      { key: 'studentMembers', label: 'Total Members', type: 'number', required: true },
      { key: 'activitiesConducted', label: 'Activities Conducted', type: 'number' },
      { key: 'majorEvents', label: 'Major Events', type: 'text' },
      { key: 'awards', label: 'Awards/Recognition', type: 'text' },
      { key: 'affiliatedTo', label: 'Affiliated To', type: 'text', placeholder: 'IEEE, CSI, ACM, etc.' },
      { key: 'establishedYear', label: 'Established Year', type: 'text' },
      { key: 'budget', label: 'Annual Budget (₹)', type: 'currency' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'New'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { clubName: 'Coding Club', clubType: 'Technical', facultyCoordinator: 'Dr. Anil Kumar', studentPresident: 'Rahul Verma', studentMembers: 180, activitiesConducted: 24, majorEvents: 'CodeFest 2024, Weekly Contests', awards: 'Best Technical Club 2024', affiliatedTo: '', establishedYear: '2018', budget: 150000, status: 'Active', remarks: '50+ students placed through competitive coding' },
      { clubName: 'IEEE Student Branch', clubType: 'Professional Society', facultyCoordinator: 'Dr. Srinivas Rao', studentPresident: 'Kavya Reddy', studentMembers: 120, activitiesConducted: 15, majorEvents: 'IEEE Day, Technical Workshops', awards: 'Outstanding Student Branch Award', affiliatedTo: 'IEEE', establishedYear: '2015', budget: 200000, status: 'Active', remarks: 'Region 10 recognition' },
      { clubName: 'Robotics Club', clubType: 'Technical', facultyCoordinator: 'Prof. Manoj Tiwari', studentPresident: 'Arjun Nair', studentMembers: 75, activitiesConducted: 12, majorEvents: 'Robo Wars, Line Follower Competition', awards: '2nd place - National Robotics Challenge', affiliatedTo: '', establishedYear: '2019', budget: 250000, status: 'Active', remarks: 'Built 5 working prototypes' },
      { clubName: 'Google Developer Student Club', clubType: 'Technical', facultyCoordinator: 'Dr. Priya Sharma', studentPresident: 'Sneha Gupta', studentMembers: 200, activitiesConducted: 20, majorEvents: 'Solution Challenge, DevFest, Study Jams', awards: 'Top 100 Global Solution Challenge', affiliatedTo: 'Google', establishedYear: '2020', budget: 100000, status: 'Active', remarks: 'Active open source contributions' },
      { clubName: 'CSI Student Chapter', clubType: 'Professional Society', facultyCoordinator: 'Dr. Venkat Reddy', studentPresident: 'Amit Shah', studentMembers: 90, activitiesConducted: 10, majorEvents: 'CSI National Convention, Hackathon', awards: 'Best CSI Chapter - South Region', affiliatedTo: 'CSI', establishedYear: '2016', budget: 120000, status: 'Active', remarks: '' },
    ],
  },
  {
    id: 'student-chapters',
    label: 'Student Chapters',
    icon: 'BookMarked',
    description: 'Professional society student chapters - IEEE, CSI, ACM, ISTE, SAE, IETE',
    fields: [
      { key: 'chapterName', label: 'Chapter Name', type: 'text', required: true },
      { key: 'society', label: 'Professional Society', type: 'select', required: true, options: ['IEEE', 'CSI', 'ACM', 'ISTE', 'SAE', 'IETE', 'IEI', 'ASME', 'Other'] },
      { key: 'chapterId', label: 'Chapter ID/Code', type: 'text' },
      { key: 'facultyAdvisor', label: 'Faculty Advisor', type: 'text', required: true },
      { key: 'chairperson', label: 'Student Chairperson', type: 'text' },
      { key: 'totalMembers', label: 'Total Members', type: 'number', required: true },
      { key: 'newMemberships', label: 'New Memberships (This Year)', type: 'number' },
      { key: 'eventsOrganized', label: 'Events Organized', type: 'number' },
      { key: 'conferencesAttended', label: 'Conferences Attended', type: 'number' },
      { key: 'papersPublished', label: 'Papers Published', type: 'number' },
      { key: 'awards', label: 'Awards/Recognition', type: 'text' },
      { key: 'annualFee', label: 'Annual Membership Fee (₹)', type: 'currency' },
      { key: 'status', label: 'Status', type: 'select', options: ['Active', 'Inactive', 'Under Formation'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { chapterName: 'IEEE Student Branch', society: 'IEEE', chapterId: 'STB12345', facultyAdvisor: 'Dr. Srinivas Rao', chairperson: 'Kavya Reddy', totalMembers: 120, newMemberships: 45, eventsOrganized: 15, conferencesAttended: 5, papersPublished: 8, awards: 'Outstanding Student Branch Award 2024', annualFee: 1500, status: 'Active', remarks: 'R10 exemplary branch' },
      { chapterName: 'ACM Student Chapter', society: 'ACM', chapterId: 'ACM-SC-456', facultyAdvisor: 'Dr. Anil Kumar', chairperson: 'Rohan Desai', totalMembers: 85, newMemberships: 30, eventsOrganized: 10, conferencesAttended: 3, papersPublished: 4, awards: 'Best New Chapter Award', annualFee: 1200, status: 'Active', remarks: 'ICPC participation' },
      { chapterName: 'ISTE Student Chapter', society: 'ISTE', chapterId: 'ISTE-789', facultyAdvisor: 'Prof. Manoj Tiwari', chairperson: 'Preethi Nair', totalMembers: 200, newMemberships: 80, eventsOrganized: 12, conferencesAttended: 2, papersPublished: 6, awards: 'Best ISTE Chapter - State Level', annualFee: 500, status: 'Active', remarks: 'Largest chapter in university' },
      { chapterName: 'SAE India Collegiate Club', society: 'SAE', chapterId: 'SAE-COLL-321', facultyAdvisor: 'Dr. Rajesh Gupta', chairperson: 'Karthik Rajan', totalMembers: 60, newMemberships: 25, eventsOrganized: 8, conferencesAttended: 4, papersPublished: 2, awards: 'Best Design Award - SAE BAJA', annualFee: 800, status: 'Active', remarks: 'BAJA & Efficycle teams' },
    ],
  },
  {
    id: 'student-achievements',
    label: 'Student Achievements',
    icon: 'Award',
    description: 'Individual student achievements, competitions, and recognitions',
    fields: [
      { key: 'studentName', label: 'Student Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text', required: true },
      { key: 'department', label: 'Department', type: 'text', required: true },
      { key: 'achievement', label: 'Achievement', type: 'text', required: true },
      { key: 'competition', label: 'Competition/Event', type: 'text' },
      { key: 'level', label: 'Level', type: 'select', required: true, options: ['Department', 'College', 'University', 'State', 'National', 'International'] },
      { key: 'award', label: 'Award/Prize', type: 'text' },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'category', label: 'Category', type: 'select', options: ['Academic', 'Technical', 'Sports', 'Cultural', 'Research', 'Innovation', 'Social Service', 'Leadership'] },
      { key: 'organizingBody', label: 'Organizing Body', type: 'text' },
      { key: 'certificateAvailable', label: 'Certificate Available', type: 'select', options: ['Yes', 'No'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { studentName: 'Rahul Verma', registrationNo: 'CS2021045', department: 'Computer Science', achievement: 'Winner - Smart India Hackathon', competition: 'Smart India Hackathon 2024', level: 'National', award: 'First Prize - ₹1,00,000', date: '2024-03-20', category: 'Technical', organizingBody: 'MHRD, Govt. of India', certificateAvailable: 'Yes', remarks: 'Problem statement by ISRO' },
      { studentName: 'Meera Patel', registrationNo: 'EC2021012', department: 'Electronics', achievement: 'Gold Medal - National Science Olympiad', competition: 'National Science Olympiad', level: 'National', award: 'Gold Medal', date: '2024-02-15', category: 'Academic', organizingBody: 'Science Olympiad Foundation', certificateAvailable: 'Yes', remarks: 'AIR 5' },
      { studentName: 'Arjun Nair', registrationNo: 'ME2021078', department: 'Mechanical', achievement: 'Best Paper Award - ASME Conference', competition: 'ASME Student Conference', level: 'International', award: 'Best Paper Award', date: '2024-04-10', category: 'Research', organizingBody: 'ASME International', certificateAvailable: 'Yes', remarks: 'Paper on sustainable manufacturing' },
      { studentName: 'Sneha Gupta', registrationNo: 'CS2022034', department: 'Computer Science', achievement: 'Google Summer of Code Contributor', competition: 'GSoC 2024', level: 'International', award: 'Successful Completion Stipend', date: '2024-08-30', category: 'Technical', organizingBody: 'Google', certificateAvailable: 'Yes', remarks: 'Contributed to TensorFlow project' },
    ],
  },
  {
    id: 'student-awards',
    label: 'Student Awards',
    icon: 'Medal',
    description: 'Institutional and external awards, scholarships, and recognitions',
    fields: [
      { key: 'awardName', label: 'Award Name', type: 'text', required: true },
      { key: 'awardType', label: 'Award Type', type: 'select', required: true, options: ['Merit Award', 'Best Student', 'Research Award', 'Innovation Award', 'Leadership Award', 'Sports Award', 'Cultural Award', 'Community Service Award', 'Governor Award', 'Chancellor Award', 'External Award'] },
      { key: 'recipientName', label: 'Recipient Name', type: 'text', required: true },
      { key: 'registrationNo', label: 'Registration No.', type: 'text' },
      { key: 'department', label: 'Department', type: 'text' },
      { key: 'awardedBy', label: 'Awarded By', type: 'text', required: true },
      { key: 'date', label: 'Date', type: 'date' },
      { key: 'prizeAmount', label: 'Prize Amount (₹)', type: 'currency' },
      { key: 'level', label: 'Level', type: 'select', options: ['Department', 'Institution', 'University', 'State', 'National', 'International'] },
      { key: 'criteria', label: 'Selection Criteria', type: 'text' },
      { key: 'certificateAvailable', label: 'Certificate Available', type: 'select', options: ['Yes', 'No'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { awardName: 'Chancellor Gold Medal', awardType: 'Merit Award', recipientName: 'Kavya Reddy', registrationNo: 'CS2020001', department: 'Computer Science', awardedBy: 'University Chancellor', date: '2024-04-15', prizeAmount: 50000, level: 'University', criteria: 'Highest CGPA in graduating batch', certificateAvailable: 'Yes', remarks: 'CGPA: 9.85/10' },
      { awardName: 'Best Innovator Award', awardType: 'Innovation Award', recipientName: 'Arjun Menon', registrationNo: 'ME2021056', department: 'Mechanical', awardedBy: 'Institution Innovation Council', date: '2024-03-01', prizeAmount: 25000, level: 'Institution', criteria: 'Best innovation project of the year', certificateAvailable: 'Yes', remarks: 'Solar-powered water purifier' },
      { awardName: 'Governor\'s Award for Social Service', awardType: 'Governor Award', recipientName: 'Ananya Gupta', registrationNo: 'IT2021023', department: 'Information Technology', awardedBy: 'Governor of Telangana', date: '2024-01-26', prizeAmount: 100000, level: 'State', criteria: 'Outstanding contribution to community service', certificateAvailable: 'Yes', remarks: 'NSS volunteer - 500+ hours' },
      { awardName: 'Best Sportsperson of the Year', awardType: 'Sports Award', recipientName: 'Priya Srinivasan', registrationNo: 'EC2022015', department: 'Electronics', awardedBy: 'Sports Council', date: '2024-04-20', prizeAmount: 15000, level: 'Institution', criteria: 'Outstanding sports performance', certificateAvailable: 'Yes', remarks: 'State-level athletics champion' },
    ],
  },
  {
    id: 'events',
    label: 'Events',
    icon: 'Calendar',
    description: 'Institution, department, national, and international events organized',
    fields: [
      { key: 'eventName', label: 'Event Name', type: 'text', required: true },
      { key: 'eventCategory', label: 'Category', type: 'select', required: true, options: ['Institution Event', 'Department Event', 'National Event', 'International Event', 'Workshop', 'Seminar', 'Conference', 'Guest Lecture', 'Webinar'] },
      { key: 'eventType', label: 'Type', type: 'select', options: ['Technical', 'Cultural', 'Sports', 'Academic', 'Social', 'Awareness', 'Celebration', 'Competition'] },
      { key: 'date', label: 'Date', type: 'date', required: true },
      { key: 'duration', label: 'Duration (Days)', type: 'number' },
      { key: 'venue', label: 'Venue', type: 'text' },
      { key: 'organizer', label: 'Organizer', type: 'text', required: true },
      { key: 'chiefGuest', label: 'Chief Guest/Speaker', type: 'text' },
      { key: 'participants', label: 'No. of Participants', type: 'number' },
      { key: 'externalParticipants', label: 'External Participants', type: 'number' },
      { key: 'budget', label: 'Budget (₹)', type: 'currency' },
      { key: 'sponsorship', label: 'Sponsorship (₹)', type: 'currency' },
      { key: 'outcome', label: 'Outcome', type: 'text' },
      { key: 'status', label: 'Status', type: 'select', options: ['Completed', 'Upcoming', 'Ongoing', 'Cancelled'] },
      { key: 'remarks', label: 'Remarks', type: 'text' },
    ],
    sampleData: [
      { eventName: 'TechVista 2024 - Annual Tech Fest', eventCategory: 'Institution Event', eventType: 'Technical', date: '2024-02-20', duration: 3, venue: 'Main Campus', organizer: 'Student Council & CSE Dept', chiefGuest: 'Mr. Satya Nadella (Virtual)', participants: 2500, externalParticipants: 800, budget: 1500000, sponsorship: 800000, outcome: '30+ events, 50+ colleges participated', status: 'Completed', remarks: 'Flagship event' },
      { eventName: 'International Conference on AI & ML', eventCategory: 'International Event', eventType: 'Academic', date: '2024-03-05', duration: 2, venue: 'Convention Center', organizer: 'CSE Department & IEEE', chiefGuest: 'Prof. Andrew Ng (Virtual)', participants: 500, externalParticipants: 200, budget: 800000, sponsorship: 400000, outcome: '85 papers presented, proceedings published', status: 'Completed', remarks: 'Scopus indexed proceedings' },
      { eventName: 'Annual Sports Meet', eventCategory: 'Institution Event', eventType: 'Sports', date: '2024-01-15', duration: 5, venue: 'Sports Complex', organizer: 'Physical Education Dept', chiefGuest: 'P.V. Sindhu', participants: 1500, externalParticipants: 0, budget: 500000, sponsorship: 100000, outcome: '15 sports, 200+ medals distributed', status: 'Completed', remarks: 'Record participation' },
      { eventName: 'National Workshop on Cyber Security', eventCategory: 'National Event', eventType: 'Technical', date: '2024-04-10', duration: 2, venue: 'Seminar Hall', organizer: 'IT Department & ISEA', chiefGuest: 'Dr. Gulshan Rai', participants: 200, externalParticipants: 80, budget: 300000, sponsorship: 150000, outcome: 'Hands-on training, certifications issued', status: 'Completed', remarks: 'ISEA sponsored' },
    ],
  },
];

export const studentDevDocumentCategories = [
  { id: 'nss-reports', label: 'NSS Activity Reports & Certificates', count: 24 },
  { id: 'ncc-certificates', label: 'NCC Certificates & Camp Reports', count: 18 },
  { id: 'sports-certificates', label: 'Sports Certificates & Results', count: 45 },
  { id: 'cultural-brochures', label: 'Cultural Event Brochures & Photos', count: 30 },
  { id: 'extension-reports', label: 'Extension Activity Reports', count: 20 },
  { id: 'outreach-evidence', label: 'Community Outreach Evidence', count: 35 },
  { id: 'club-records', label: 'Club Activity Records & Minutes', count: 28 },
  { id: 'chapter-reports', label: 'Student Chapter Annual Reports', count: 12 },
  { id: 'achievement-proofs', label: 'Student Achievement Certificates', count: 60 },
  { id: 'award-certificates', label: 'Award Certificates & Citations', count: 25 },
  { id: 'event-reports', label: 'Event Reports & Proceedings', count: 40 },
  { id: 'compliance-docs', label: 'NAAC/NBA Compliance Documents', count: 15 },
];